### ISSUE TITLE
Write a script that forces the CoAP server to respond with customized message to the CoAP client

### ISSUE THREAD

**Issue by salmeghlef** [obgm/libcoap#1003]
Hello guys,
I need a script that forces the CoAP server to respond with a customized message to one CoAP client, and I need also a script that forces more than one CoAP server to respond with a dedicated message to the CoAP client. If the solution is available in the documentation, please refer me to it. 

Thank you

**Comment by salmeghlef** [comment]
Is there a library that supports what I am looking for? it is for testing of some attacks and then find a way to mitigate these attacks?

**Comment by mrdeep1** [comment]
I assume that you are referring to the amplification attack in the first instance.

A basic principle of CoAP is that it follows a request/response model - no request, no response.  There is the concept of an unsolicited response can be sent on the changing of a value of a resource on a server providing the client requested this to happen in the first place (RFC7641).  However, the sending of the unsolicited response is under the control of the server.

The amplification attacks in general come about because there are a lot of servers on lots of different IP addresses that respond to a request.  The attacking client (or clients managed by some sort of Command and Control Center) pretend to be a different IP address (the victim's IP address) when making the many requests that have amplified responses all hit the unsuspecting Victim at its IP address.

These servers are not owned by the attackers and so will only send back responses that they are configured for.  There is no real notion of the attacker being able 'customize' the server unless the server has been compromised (and then other alarm bells should be going off) and lots of them will have to be compromised.  So here, you will need to set up lots of different servers on different IP addresses with one or more clients sending the requests.

If you want to scale things back to a single server and client, then the standard libcoap examples for [coap-client](https://libcoap.net/doc/reference/develop/man_coap-client.html) and [coap-server](https://libcoap.net/doc/reference/develop/man_coap-server.html) will show you the effects of response amplification when the client requests `/example_data`.

**Comment by salmeghlef** [comment]
Thanks John, that was very helpful information. Please assume that I am running CoAP clients and CoAP servers on my local machine, so nothing goes online, just practicing the attacks on the local CoAP servers and clients. Now,

1- How to fool the CoAP servers to send the responses to a dedicated CoAP client (the victim)? (Practical example is helpful, or please refer me to some sources that help to simulate this process).

2- What commands should go from the CoAP client to the CoAP server that result in large response (message)?

3- What examples of CoAP server and client that are NOT secured with DTLS? I plan to not using DTLS for these simulations. 
Thank you always for your valuable information.

**Comment by mrdeep1** [comment]
1- Any genuine CoAP server will only respond to the source address' IP address + port as received in the CoAP request packet.  So the only way to get the CoAP server to send the response to somewhere else is for the CoAP request packet to have a fake source IP address (and possibly port).  Therefore a genuine request packet (i.e syntactically correct) needs to be cloned and the source IP address modified before the packet is sent.  This is not the right forum to discuss how to do that.

2- I had already given you the URI path to do this for the libcoap server - `/example_data` .  `coap-client coap://127.0.0.1/example_data` .

3 - I'm slightly confused by your question.  Use of `coap://` scheme will not use DTLS, whereas use of `coaps://` scheme will always use DTLS.

**Comment by salmeghlef** [comment]
Very interesting John. How about knowing the IP address or MAC address of the CoAP-Client. Is there away in libcoap project to get the MAC address or IP address of the CoAP client from the CoAP server?

**Comment by mrdeep1** [comment]
For the libcoap servers, they use `recvmsg()` to receive a request packet.  From the `msghdr `returned parameter, it is possible to get the IPv4 or IPv6 address of the sending client.  The server then sends the response back to this determined IP address.

Running the server with the -v7 option will show you the appropriate IP addresses.

Programmatically, as per the documentation see [coap_session_get_addr_remote](https://libcoap.net/doc/reference/develop/man_coap_session_get_addr_remote.html)

**Comment by salmeghlef** [comment]
Thanks John. Hope you can put some details. For instance, "Running the server with the -v7 option will show you the appropriate IP addresses." should be followed by the practical command like:

./coap-server v7  # to run the libcoap server with v7. I am not seeing in the example any versions except the original one "coap-server".

Programmatically, to get the address of the peered client:

coap://[localhost]:/get_addr_remote

and so on so forth. This is very helpful to those who wants to test libcoap for their projects and publication. Thanks again

**Comment by mrdeep1** [comment]
For how to run the server with the -v7 (note leading -) see [coap-server(5)](https://libcoap.net/doc/reference/develop/man_coap-server.html).  For how to run the client see [coap-client(5)](https://libcoap.net/doc/reference/develop/man_coap-client.html).

[coap_session_get_addr_remote](https://libcoap.net/doc/reference/develop/man_coap_session_get_addr_remote.html) is the public API call into the libcoap library which you can use in a C or C++ program to determine the information about the IP address / port of the remote end of the session.

**Comment by salmeghlef** [comment]
The CoAP server refuses to use -Put method to send some example_data to the other client. Based on the documentation, it says don't use it with local addresses such as "tun" devices, any idea please,,

![Untitled](https://user-images.githubusercontent.com/45724031/210188906-d0537fdb-2c43-4fea-8a54-e7c799beb92e.jpg)

**Comment by mrdeep1** [comment]
Firstly, you are confusing terminology of server and client.  Here, you are using the **client** (as you are using `coap-client`) to send a request to a **server** (doing a PUT request with data of "hello").

Secondly, as you do not have a server listening on port 55536, your target host's TCP/IP stack is sending back an ICMP diagnostic message stating that there is not a server available on that port "`coap_network_read: ICMP: Connection refused`".  You need to be running a server listening on that port.  Try running `coap-server -p 55536 -v7` .

Yes, you can set up tun / tap devices (which is out of the scope of this forum), but from the coap-client / coap-server perspective they just need to use a network that is capable of routing IP traffic as needed (again out of the scope of this forum).

**Comment by salmeghlef** [comment]
I do understand now John. What is the best or say easiest way to force the server to send /example_data to other client. In other words, I need to spoof the IP of the other client so I can send the request from client_1 and the response goes to client_2. If I need a C code to spoof, where should that code placed at? server side or client side? Thanks a lot.

**Comment by mrdeep1** [comment]
In general (unless the server has been compromised) the CoAP based servers used in amplification attacks will be running standard, un-modified code.  It is the rogue clients that are causing the amplification trouble and it is these rogue clients that need modification, or the network environment that the clients are running in modify the source IP address of the request packet (e.g. by using NAT).  Again, how you do that is outside of this forum.

**Comment by salmeghlef** [comment]
If that is the case John, what is the benefit of the "PUT" method in the CoAP URIs? PUT method is to send something to "others" not "mine"!

**Comment by mrdeep1** [comment]
C code `examples/coap-rd.c` makes use of `coap_session_get_addr_remote()` (code needs fixing for IPv4) from the current session to get and print out the IP address / port.

**Comment by salmeghlef** [comment]
Assume that I am running ONE CoAP server and ONE CoAP client, no in details (please) how to use examples/coap-rd.c to get the IP addresses of both (server and client). Detailed steps will result in ending this issue, thank you

**Comment by mrdeep1** [comment]
As stated in #995 I do not have the time to provide code (or craft and test a set of detailed instructions) for you.  There is nothing stopping you parsing the log output to abstract the IP addresses as can be seen in the output you provided in https://github.com/obgm/libcoap/issues/1003#issuecomment-1368584499

**Comment by salmeghlef** [comment]
Thanks John, that was a great help from you.

**Comment by mrdeep1** [comment]
Several things here.

In the TCP/IP stack layer 2 the IP addresses are defined in the network packet.  The source and destination IP MUST be the same type, namely both IPv4 or IPv6, not a mixture.  So `10.211.55.3` and `::1` mixture is illegal and will always get rejected.

Any correctly performing TCP/IP network stack will only allow you to specify the source IP address (the IP address that is bound to - hence bind() error) MUST be the IP address as defined on one of the network interfaces (as shown by` ifconfig -a` (linux)).

**Comment by salmeghlef** [comment]
Please guide how to assign each coap-client on its dedicated interface
.

.
![assigned_2](https://user-images.githubusercontent.com/45724031/210545954-46de0b3b-6754-4870-ab3f-b7d1d43cf32a.jpg)

**Comment by mrdeep1** [comment]
@salmeghlef Can this issue now be closed off?

**Comment by salmeghlef** [comment]
Before closing, this Nmap tool https://nmap.org/nsedoc/scripts/coap-resources.html is designed to spoof random IP addresses (Decoy based method) to flood the coap-client with fake requests. Now, can someone help to use this tool for the "PUT" method to amplify the coap-client instead of the basic "GET" method used in this tool.

**Comment by mrdeep1** [comment]
A "PUT" request from a client is less likely to cause an amplified response (response_packet_size / request_packet_size > 1) than a "GET" request from a client.  The Nmap documented example does generate an amplified response.

How you modify Nmap parameters is beyond the scope of this forum.

**Comment by salmeghlef** [comment]
Who is the victim when using the Nmap tool. Is it the coap server? or the client that is going to receive a huge data (>1024 byte) such as example_data which exceeds 1024 byte.

**Comment by mrdeep1** [comment]
For an amplification attack, there are many clients spoofing the victim's IP address so that all the server responses arrive at the victim's IP.  Usually, the spoofing clients use many real servers so the sum of the real servers responses overwhelms the victim's IP address.

So, if Nmap spoofs IP addresses of the victim when sending the requests, it is the client part of the protocol that is being spoofed and so the victim IP gets all the CoAP server responses.

**Comment by salmeghlef** [comment]
Can you please test the Nmap tool and see if it is doing what you are talking about. I do understand you but not sure if the Nmap tool is doing what you talk about.

**Comment by mrdeep1** [comment]
The last time I played with Nmap was over 25 years ago and I am sure things have changed since then.  I have no desire or time to use Nmap again.

> So, if Nmap spoofs IP addresses of the victim when sending the requests, it is the client part of the protocol that is
> being spoofed and so the victim IP gets all the CoAP server responses.

Your updated question with picture shows exactly what I was saying.  I would then expect multiple Nmap clients and unsuspecting CoAP servers to be at multiple IP addresses, of which 5.5.5.5 is one, to be sending the responses to 1.2.3.4.

**Comment by salmeghlef** [comment]
Based on your valuable information, the target is qualifying the victim in the Nmap tool as shown in the picture.

![Screen Shot 1444-06-23 at 7 37 29 PM](https://user-images.githubusercontent.com/45724031/212728046-3b95c942-0b95-46ae-9df6-de580ff1fbcb.png)

However, when I check the wireshark, I am seeing a request from a fake IP to the server, but the response goes back to the fake IP. So, testing in couple of minutes will help to close this issue with great gratefulness.

**Comment by mrdeep1** [comment]
> However, when I check the wireshark, I am seeing a request from a fake IP to the server, but the response goes
> back to the fake IP. So, testing in couple of minutes will help to close this issue with great gratefulness.

That I would expect if you are using the -D option but not otherwise.  Packets are obeying the standard network rules of where to send / route  packets.

`<target>` is the coap server IP address that is to be "scanned" by Nmap to see if it is alive or not.  I do not think it is the Victim IP address - that would be created by the `-D` option.

**Comment by salmeghlef** [comment]
Thanks a lot Mr. Jon. I am so grateful for your help and patience. I am done with my experiment. You can now proceed to close of this issue.

**Comment by mrdeep1** [comment]
Thanks.  Closing now.
