### ISSUE TITLE
Sending COAP requests to different servers. 

### ISSUE THREAD

**Issue by fbucafusco** [obgm/libcoap#1028]
Hi ! 
I wonder if I can send COAP requests to different servers ip : ports.
As far I could analyze, the only way would be to create several sessions (since the host and port is configured at session level) but it there any possibility for sending rqsts to different host ips and ports using the same session? 
Thanks in advance

**Comment by mrdeep1** [comment]
Using the same session is likely to be problematical - especially if there are transfers that require multiple blocks per payload that need to request the next block(s) to be transferred - but which `host:ip` is the subsequent request going to be against.  Likewise any CON requests that need to be re-transmitted because of timeout could be an issue.

The client logic does do a `connect()` when setting up the UDP session which may cause issues with the TCP/IP stack with the `host:ip` continually changing.

Certainly this would never work for TCP based sessions.

The client does support having multiple sessions (all need to be set up with the `coap_new_client_session*()` functions).  Apart from the memory overhead of multiple session structures (which can be released using `coap_session_release()` when no longer required) is there a reason why you need to do this?

**Comment by fbucafusco** [comment]
Thanks for the answer.
