### ISSUE TITLE
Is there a memory leak when lots of packets need to be send?

### ISSUE THREAD

**Issue by WWWangHan** [obgm/libcoap#1055]
## Environment

- libcoap version (release-4.3.0, i use git branch to find it):

- Build System:             [CMake]
- Operating System:         [Linux]
- Operating System Version: [Linux version 5.4.0-137-generic]
- Hosted Environment:       [None]

## Problem Description

When the coap client or coap server need to send a lot of packets, is it possible that the packets cannot be processed immediately? At this point it looks like a memory leak?

I found this in the related logs: 
coap_network_send: Operation not permitted

But i'm not sure if there will be an impact here, because looking at the coap_send_internal function, i found:
The memory that is allocated for the pdu will be released by coap_send_internal(). The caller must not use the pdu after calling coap_send_internal().

On the other hand, i tried using a stack parser tool to see the memory allocation flow, and here are the relevant results:
CoapPackToPdu()->coap_add_data()->coap_add_data_after()->coap_pdu_resize()->realloc()

There is another question I would like to ask. Will coap consider supporting broadcasting? Any help will be appreciated, thanks.

### Expected Behavior

There is no so-called memory leak, and all PDUs are released normally.

### Actual Behavior

It seems that there is a memory leak phenomenon, and when there are a lot of packets, it will reach the GB level.

### Steps to reproduce
This is a problem reported by big data, and the reproduction requires the device to send a large number of data packets.
There are many devices in the environment, and they need to send and reply when they receive each other's messages.

**Comment by mrdeep1** [comment]
Thanks for raising this - memory leaks are always a challenge to track down.

Some observations / questions

Is this a server or client issue, or are you seeing it for both?

If it is release 4.3.0., then there have been a lot of changes over the last (almost) 2 years, and there could well have been some memory leaks fixed during  that time.  It would be good to confirm the version you are actually using (`git describe --tags --always`).

If the packet transmission is using CON, then the PDU is kept until the transmission is acknowledged by the remote end, or the re-transmits have timed out (which can be 93 secs with default values).

If large payloads are being transmitted over multiple packets, then the tracking mechanism for this large payload could be around for some time.

Servers cache client sessions in case they get re-used, and this could build up over time.  It is possible to define maximum number of "idle" sessions using [coap_context_set_max_idle_sessions(3)](https://libcoap.net/doc/reference/develop/man_coap_context_set_max_idle_sessions.html).

Using valgrind may help you to track down leaks at application exit.  Note that you need to free off memory that the application has allocated before the application exits, as well as calling `coap_session_release(session)` (clients only), `coap_free_context(context)` and `coap_cleanup()` before the exit.

> coap_network_send: Operation not permitted

This does concern me a bit - why your client or server does not have permission to` send()`, `sendto()` or `sendmsg()` a packet.  I am assuming that you are using IPv4 or IPv6 here.  It could be that you have some sort of iptables overflow here (i.e connection tracking overflow).

> CoapPackToPdu()->coap_add_data()->coap_add_data_after()->coap_pdu_resize()->realloc()

This is expected behavior as the PDU is being resized to hold the larger amount of data.

> Will coap consider supporting broadcasting?

libcoap has support for multi-casting (IPv6 has no real notion of broadcasting) for both IPv4 and IPv6, following the appropriate RFC specifications.  Note that only NON type CoAP packets are supported, and (D)TLS is not supported.  There are internet drafts for supporting OSCORE.

**Comment by mrdeep1** [comment]
@WWWangHan Did you manage to get anywhere with this?

**Comment by mrdeep1** [comment]
@WWWangHan Did you manage to get anywhere with further troubleshooting this?

**Comment by WWWangHan** [comment]
Sorry for the late reply, i'm doing some testing and upgrading libcoap during this time.

Is this a server or client issue, or you seeing it for both?
Both.

The specific libcoap version, use git describe --tags --always
c269acd

Because it is suspected that the packets are not processed in time, make it looks like a memory leak. Therefore, the number of devices and the number of function calls are appropriately reduced, and it seems that there is no such problem now.

At the same time, the upgrade work has been completed, and it has been switched to version 4.3.1. It will take some time to observe whether there will be similar problems.

Thanks again for your help, can i close the issue? If i find the same problem, i will reopen it, because the test time will be longer.

**Comment by mrdeep1** [comment]
Closed for now.  If still an issue, pleas re-open it.
