### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by h0ru5** [obgm/libcoap#126]
Hi,

to make it easier to integrate libcoap into build chains, especially embedded Linux (e.g. yocto etc.), CMake would be a great help.
Generally, it seems as CMake is becoming the next popular C/C++-build tool.

It's possible to integrate it via `ExternalProject_Add() ` (but quite tricky and leaves you with a lot of build-time dependencies)
Its better to port from the autotools build and provide a CMakeLists.txt (at least in parallel).

Regarding the build steps of the autoconfig files:
What gets configured?
Besides compiler checking, all they do is setting the version and locating SSL libs, right?

**Comment by tijuca** [comment]
> Generally, it seems as CMake is becoming the next popular C/C++-build tool.

That's something I read now for about 8 years or so from time to time but I don't think so. CMake make mostly thing differently, but not necessarily better.

As configure.ac is processed by autoconf to generate the configure script from it you will find all the answers to your questions if you look into configure.ac. Yous will see there more or less easy to read functions and variable  definitions like *CFLAGS or *LIBS. and some logic that is needed for getting later a successful build depending on what the user has configured. So it's not that easy to say what the configure script is doing, because you will need a deeper knowledge about the configuration anyway if you want to get the build triggered and controlled from some external system.

**Comment by obgm** [comment]
With merger of #430, we now have CMake as optional build tool besides the well-established GNU tools. Therefore, I am closing off this issue.
