### ISSUE TITLE
using libcoap with custom connection multiplexing

### ISSUE THREAD

**Issue by dmosberger** [obgm/libcoap#130]
I'd like to use libcoap within an existing framework which uses the Linux **epoll()** interface for connection multiplexing.  The **coap_run_once()** interface in the develop branch does not fit my needs well since it is **select()**-based and there is no way of registering other (non-CoAP) file descriptors.

It seems to me that if there were a **coap_read()**-like function that operates on a specific session instead all the sessions of a context, that would get close.  The function would also have to take a parameter indicating whether the session is readable, writable, or in an exception status (so that socket->flags can be updated).

Is there any reason not to add such functionality to libcoap?

Thanks for your good work and looking forward to a response!

**Comment by obgm** [comment]
In theory, it should already work as desired. `coap_write()` allows to pass the sockets to write to, while `coap_read()` simply checks the sockets' flags. By setting `COAP_SOCKET_CAN_*` appropriately, you should be able to control operation from your main loop.

**Comment by dmosberger** [comment]
OK, I think I get coap_read(), but coap_write() seems like a rather unusual interface to me.  If I understand the code right, it collects all the sockets in a context that want I/O (read or write) and then takes care of (re-)sending any pending messages.  But if I already know that file-descriptor N is writable, it doesn't look to me like there is any way to use coap_write() to handle only that descriptor.  Am I missing something?

**Comment by obgm** [comment]
Now that you are saying this... Yes, this is a bit unusual. @jcmichelou?

**Comment by dmosberger** [comment]
Maybe the intent for coap_write() is to call it periodically to check what sessions need packet retransmissions and then take care of those retransmits.

However, if on some of those sessions the packets cannot be sent immediately, it'd then be necessary to select/poll on the underlying file descriptor until it becomes writable again, and then you'd have to trigger the retransmit again somehow (which coap_write() could do, but perhaps isn't ideal for).  Maybe this case rarely happens with UDP or DTLS but CoAP over TCP could see that quite easily, I imagine.

Regardless, it'd be very helpful to have some documentation on how coap_read()/coap_write() are intended to be used.

**Comment by jcmichelou** [comment]
I did not document these functions extensively since they were not public functions before I added coap_session_t.
coap_run_once() is a straightforward example of how you use these two functions. I think the confusion comes from the names which predate TCP support and blocking writes handling, and actually coap_read() does both reads and writes.
Basucally coap_write() is an API to gather the list if file descriptors to wait on, for example with epoll. It also returns the timeout for this wait. When either the timeout is reached or at least one of the file descriptors becomes readable/writable, then coap_read() must be called to handle the new incoming messages and/or complete blocked writes, then coap_write() shall be called again to poll for the new set of blocked file descriptors.
If you want to use epoll, you probably will need to compare the list of fd and flags returned by coap_write with the previous list and call epoll_ctl() accordingly, then after epoll_wait() you should update the flags before calling coap_read().

**Comment by jcmichelou** [comment]
To answer your questions more directly, forget about the names. You don’t call coap_write() because you know an fd is writable, you call coap_write() to get the list of fds to poll. Then once you know an fd is writable, you set the COAP_CAN_WRITE flag on it, and all other writable fds, then call coap_read() which will handle all blocked writes/reads/connects/accepts.
coap_write() also does some writes in some cases, but only for UDP and DTLS and these are never blocking.

**Comment by jcmichelou** [comment]
By the way, maybe there is a misunderstanding about packets handling on UDP sockets. For UDP/DTLS, all writes are non-blocking and poll/select is not used. If the UDP queue is full (which would require quite a few CoAP packets in the queue on a standard linux kernel), then packets are dropped. They will be retransmitted later according to CoAP rules and type of packet.

**Comment by mrdeep1** [comment]
epoll using an exposed single file descriptor per coap context is available in PR #347

**Comment by mrdeep1** [comment]
@dmosberger Now that epoll is available (on Linux systems) in the develop branch, can this now be closed off?

**Comment by dmosberger** [comment]
I haven't had a chance to play with it, but yes, it looks like exactly what I need.  Thanks!
