### ISSUE TITLE
Custom Functions for I/O Operations

### ISSUE THREAD

**Issue by bathooman** [obgm/libcoap#1326]
Hello,

I am inquiring about the capability of libcoap to allow specifying custom functions for I/O operations. My current understanding suggests that libcoap does not provide this flexibility. Notably, I observe that there is an overlap in the contributors between libcoap and TinyDTLS. By way of illustration, TinyDTLS offers an approach to customizing I/O functions as shown below:

```
static dtls_handler_t cb_psk = {
    .write = send_to_peer_client,
    .read = read_from_peer_client,
    .event = NULL,
    .get_psk_info = get_psk_info_client,
    .get_ecdsa_key = NULL,
    .verify_ecdsa_key = NULL
};
```
Thanks for your time.

**Comment by mrdeep1** [comment]
There is a coap_netif_ layer that is called by libcoap upper level functions to handle any I/O.  See https://libcoap.net/doc/reference/develop/group__netif__internal.html for details about those functions.

This netif layer then calls various coap_socket_*() functions.   To support different environments (Posix, LwIP, Contiki RIOT) there are different coap_io{Type}.c files.

There is need for support for custom I/O functions that goes beyond read/write - for example connect/accept.

You need to explain further what you are trying to do here.

**Comment by bathooman** [comment]
Thank you for your response. I specifically want to be able to handle the I/O operation using my custom function. For example, when the packet is ready to be sent, my specified function is called (e.g. `send_to_peer_client`) . Similarly, when a peer wants to receive a packet, my specified function is called (e.g. `read_from_peer_client`).

**Comment by mrdeep1** [comment]
Having custom functions for read/write should be fairly simple to implement.  However, any 'data flow session' will still need to be set up / torn down (where is this packet being sent - via what medium etc) by the app, but libcoap will need to know that this has been done. (So does TinyDTLS).

You also need to specify a mechanism for indicating that a new packet is ready to be received, so that the read function can be invoked.

For Datagram transport reads, they need to update where the packet is coming from / going to so that the libcoap logic can determining which (possibly new) 'data flow session' is in use.  In a similar vein, TinyDTLS read/write has to update other information as well as just sending/receiving the packet.

Are you trying to do this across a UDP/TCP transport connection, or something else?

**Comment by bathooman** [comment]
Thank you for your response. On high level, as you might know, I am trying to test the implementation for different properties. More specifically, I want to run specific scenarios on top of UDP transport connection. At the same time, I don't want to modify the implementation intrusively. Rather I prefer to achieve this through a test harness.

**Comment by mrdeep1** [comment]
It is good that you are testing out the code, looking for possible issues.

Modifying the code in any way to set up your test harness may introduce new issues / fail to find any issues specifically with the read/write logic.

If you want to test input UDP packets, then I suggest you set up a fairly standard server listening on a known IP/port.  Then write a UDP packet generator program that sends 'random' UDP packets to the known IP/port and silently (i.e. not send back an ICMP diagnostic error message) drops any responding packets.
