### ISSUE TITLE
Observe functionality challenges

### ISSUE THREAD

**Issue by mrdeep1** [obgm/libcoap#147]
It currently is not intuitive as to how to get CoAP Observe to work

*Setting up Observe*
a) Enabling Observer
resource->observable = 1;
b) Triggering a Observe to get sent
coap_resource_set_dirty(resource, NULL);
c) Getting the actual observe packet sent
coap_check_notify(ctx); /* Done in the main IO processing loop */

I would like to see this
a) coap_set_resource_get_observable(resource)
b) coap_resource_trigger_observe(resource)
c) coap_check_notify(ctx) should be done internally by coap_write(), and the application need not do it at all

*GET handler calling - determining Uri*
When the GET handler is called by handle_request(), the request parameter is set.
When the GET handler is called by coap_check_notify(), the request parameter is not set.

'request' not getting set will catch some people out - I can document this in a man page.  However, getting the Uri requires knowledge of the implementation and used of resource->uri.  I would like to see a coap_resource_get_uri(resource) function.

If you are happy with all of this, I will create a PR and do it.

**Comment by obgm** [comment]
Please do. Especially the manual call to `coap_check_notify()` is less than optimal.

**Comment by baw-serafin** [comment]
Sounds nice: But I don't get the "GET handler calling - determining Uri" part.

I think the handler does not even have to know if it is a notify or a get. In the notify case the observe option should already be set in the response (y should the handler do this?).

Getting the uri in the handler should also be a none issue. There is no reason to do that. If you need that to fetch the correct value / context you better use the user_data pointer introduced in #152. Having the request set is probably still a good Idea to avoid unexpected null pointers (specially if there is no longer a reason to differentiate between get and notify)

**Comment by mrdeep1** [comment]
My use case is having potentially 100s or 1000s of (dynamically coming and going) resources being monitored.  Having separate handler code instantiated for each of them makes no sense, so there is a common handler.  I need to determine from the "resource" (Uri-Path + Uri-Query), used as a key lookup, what details to respond with.  

My note about request is that we cannot rely on the request to be there in the GET handler - so need to get the uri portion out of the resource that is passed in.  To me, coap_resource_t should be opaque as possible, hence the inline function coap_resource_get_uri().

Your #152 update does not help me here as an observe can also be based on the query, so I can easily have 2 or more observers against the same resource which is uri path based.

The GET handler has to set the Observe option (and Max-Age) as it is unsafe to do it in libcoap because the Options can only be added to the PDU in numerically incrementing order.  (e.g. COAP_OPTION_CONTENT_TYPE added by the GET handler can only go after COAP_OPTION_OBSERVE and before COAP_OPTION_MAXAGE)

Building a fake 'request' to pass into the GET handler can be done for notify, but there is no need to do that and potentially complicates things if not build exactly as the original GET request.

I guess this discussion is all about why we need to get this properly documented - hence why, when I get time, I want to get the code simplified / more logical (no need to copy a lot of stuff out of examples/client.c into every other client when all it needs  is a set of simple library functions) and put into a man page.

**Comment by baw-serafin** [comment]
@mrdeep1 Thats more or less exactly the use case I had in mind with my change. You just add the things you would like to fetch with the uri as key directly to the resource so no inefficient and error prone string handling required.

**Comment by hongnguyen-tma** [comment]
Sorry if my question is not related to your topics. I was looking in the source code, but haven't found the answer yet. Has the following feature been supported? 

RFC 7641
<< 3.6 Cancellation
A client that is no longer interested in receiving notifications for
   a resource can simply "forget" the observation.  When the server then
   sends the next notification, the client will not recognize the token
   in the message and thus will return a Reset message.>>

[In case this hasn't been supported yet] 
I'm thinking of something like this. Could you tell if it's reasonable? 
 + The client saves the token of its previous request in its local storage. 
 +  It simply deletes the stored token if it wants to "forget" the observation. 
 +  The client must provides interface or option (e.g forget-token) so that the client executor side can control deleting the stored token at any time.

Thanks
Hong

**Comment by obgm** [comment]
@hongnguyen-tma This is implemented in libcoap. The RST method is designed such that clients that have lost their state (e.g., due to reboot) can finish the observe relationship. Usually, a cleaner method would be employed to cancel an existing observe relationship by sending a `GET` with `Observe: 1` for the observed resource.

**Comment by mrdeep1** [comment]
Hi Hong,

Two responses

1) When a client drops the session that an observe is active on (e.g. by a client restart), the next unsolicited update will cause a RST response to get generated by libcoap.  Alternatively, as Olaf says, if the client no longer wants these updates, then it should send a GET request (with the correct token and resource) with the observe option value set to 1 to tell the server that it is unsubscribing from the resource/token.  As the RST is automatically generated when the session "goes away", the client does not need to un-subscribe the resource/token first.

) There are 2 parts to setting up the observe logic.  The client and the server.  You are correctly describing what currently has to be done on the server.  The client also needs to "subscribe" by setting the CoAP Option COAP_OPTION_OBSERVE with a value of 0 in a GET request PDU.  Once subscribed to the resource using a defined token, coap_resource_set_dirty() will then trigger a response packet to get sent to the client.

**Comment by obgm** [comment]
Currently, any notification is passed to the application layer because libcoap does not keep track of the client-side subscriptions. The callback function currently would have to generate the RST. Even worse, if the notification was confirmable, libcoap would acknowledge it automatically, with the side-effect that the sender of the notification might ignore the RST because it has already cleared its message state, and hence keep sending notifications. I think that has been discussed before but seems not to have been resolved until now?

**Comment by obgm** [comment]
As a side note: The actual values for the `COAP_OPTION_OBSERVE` should be `COAP_OBSERVE_ESTABLISH` and `COAP_OBSERVE_CANCEL`, of course.

**Comment by mrdeep1** [comment]
I have updated the man page for coap_observe (in a separate pull request) to say the following reflecting on the comments above (the man page does describe some functions that are not available until the update is pushed)

`RFC 7641 extends the CoAP protocol to be able to monitor the state of a
resource over time.

This enables clients to "observe" resources with a defined query, i.e., to
retrieve a representation of a resource and keep this representation updated
by the server over a period of time.

The server has to flag a resource as "observable", and then the client has
to request in a GET request that it wants to observe this resource by the use
of the COAP_OPTION_OBSERVE Option with a value of COAP_OBSERVE_ESTABLISH.
Optionally, the client can specify query options for the resource.

The underlying library adds in and removes "subscribers" to the resource as
appropriate in the server side logic.

Within the server application, it needs to determine that there is a change of
state of the resource under observation, and then cause the CoAP library
layer to initiate a "fake GET request" so that an unsolicited GET response
gets sent back to all the clients that are observing the resource.  The
appropriate GET handler within the server application is called to fill in the
response packet with the appropriate information.

Whenever the server sends a copy of the state of the "observed" resource to
the client, it will use the same token used by the client when the client
requested the "observe".  The client will receive this unsolicited response
in the handler defined by coap_register_response_handler().  It is the
responsibility of the client application to match the supplied token and
update the appropriate internal information.`

**Comment by mrdeep1** [comment]
Fixed by Pull Request #153
