### ISSUE TITLE
setting coap_endpoint_set_default_mtu(x) causes messages to be resent when message size is bigger than x.

### ISSUE THREAD

**Issue by rakeshksahu** [obgm/libcoap#1485]
## Environment

- Build System:             CMake
- Operating System:         Linux
- Operating System Version: [ ]
- Hosted Environment:       [None]

## libcoap Configuration Summary

If get_config,sh exists, please copy the output from (do in the top level libcoap directory) :-
```
./get_config.sh
Last ./configure build

libcoap package version        : "4.3.5rc2"
libcoap package source         : "v4.3.5-rc2-24-g48b56aa8"
libcoap API version            : "3"
libcoap ABI version            : "3.1.2"
libcoap libtool SO version     : "4.2.1"
libcoap DTLS lib extn          : "-openssl"
host system                    : "arm-poky-linux-gnueabi"
build with server support      : "yes"
build with client support      : "yes"
build with IPv4 support        : "yes"
build with IPv6 support        : "yes"
build with Unix socket support : "yes"
build with TCP support         : "yes"
build DTLS support             : "yes"
   -->  OpenSSL around         : "yes" (found OpenSSL 1.1.1w)
        OpenSSL_CFLAGS         : ""
        OpenSSL_LIBS           : "-lssl -lcrypto"
add default names              : "yes"
build Observe Persist          : "yes"
build using epoll              : "yes"
enable small stack size        : "no"
enable separate responses      : "yes"
enable OSCORE support          : "yes"
enable Q-Block support         : "yes"
enable max logging level       : "none"
enable thread safe code        : "yes"
enable recursive lock check    : "yes"
build doxygen pages            : "yes"
    --> Doxygen around         : "yes" (/usr/bin/doxygen 1.9.1)
       -->  dot around         : "yes" (/usr/bin/dot 2.43.0)
build man pages                : "no"
build unit test binary         : "no"
build examples                 : "yes"
install examples source        : "yes"
build with gcov support        : "no"
build shared library           : "yes"
build static library           : "yes"

```
## Problem Description

We want to restrict the mtu size in libcoap to lets say 512. But when we set it, and any response message is greater than 512 than messages are getting retransmitted again and again and at last getting failed at client side.
when we are setting coap_endpoint_set_default_mtu(x) causes messages to be resent when message size is bigger than x.

### Expected Behavior

response to be successfully received at client side.

### Actual Behavior

response getting retransmitted again and again at server side.

### Steps to reproduce

1. 
2. ...

### Code to reproduce this issue

```cpp
#include "coap3/coap.h"

void main()
{
//coap setup part.

coap_context_set_block_mode(
          m_coap_ctx, COAP_BLOCK_USE_LIBCOAP | COAP_BLOCK_TRY_Q_BLOCK);
/*start - inside resource handler code. while sending back the response. assuming data.size is more than 512*/
coap_add_data_large_response(resource,
                                         session,
                                         request,
                                         response,
                                         query,
                                         COAP_MEDIATYPE_APPLICATION_CBOR,
                                         0x2ffff,
                                         0,
                                         data.size(),
                                         data,
                                         nullptr,
                                         nullptr);
/*end - inside resource handler code */

/*Is this how it should be? Am I missing something?*/
}

```
## Debug Logs

```
DAEMON.INFO: Jul 24 10:05:59.613 DEBG ** 127.0.0.1:9909 <-> 127.0.0.1:58459 (if1) DTLS: lg_xmit 0x5f7990 initialized
DAEMON.INFO: Jul 24 10:05:59.614 DEBG ** 127.0.0.1:9909 <-> 127.0.0.1:58459 (if1) DTLS: mid=0xa7ca: delayed
DAEMON.INFO: Jul 24 10:05:59.617 DEBG *  127.0.0.1:9909 <-> 127.0.0.1:58459 (if1) DTLS: netif: sent   41 bytes
DAEMON.INFO: Jul 24 10:05:59.618 DEBG *  127.0.0.1:9909 <-> 127.0.0.1:58459 (if1) DTLS: dtls:  sent    4 bytes
DAEMON.INFO: v:1 t:ACK c:0.00 i:5541 {} [ ]
DAEMON.INFO: Jul 24 10:06:00.620 DEBG *  127.0.0.1:9909 <-> 127.0.0.1:58459 (if1) DTLS: netif: recv   41 bytes
DAEMON.INFO: v:1 t:ACK c:0.00 i:a7c9 {} [ ]
DAEMON.INFO: Jul 24 10:06:00.620 DEBG ** 127.0.0.1:9909 <-> 127.0.0.1:58459 (if1) DTLS: mid=0xa7c9: removed (1)
DAEMON.INFO: Jul 24 10:06:00.621 DEBG ** 127.0.0.1:9909 <-> 127.0.0.1:58459 (if1) DTLS: mid=0xa7ca: transmitted after delay
DAEMON.INFO: Jul 24 10:06:00.622 DEBG *  127.0.0.1:9909 <-> 127.0.0.1:58459 (if1) DTLS: netif: sent  311 bytes
DAEMON.INFO: Jul 24 10:06:00.622 DEBG *  127.0.0.1:9909 <-> 127.0.0.1:58459 (if1) DTLS: dtls:  sent  274 bytes
DAEMON.INFO: v:1 t:CON c:2.03 i:a7ca {} [ ETag:0x02, Content-Format:application/cbor, Max-Age:196607, Block2:0/M/256, Size2:419 ] :: binary data length 256
```

[client_log.txt](https://github.com/user-attachments/files/16361504/client_log.txt)
[coap_dtls_server_log.txt](https://github.com/user-attachments/files/16361507/coap_dtls_server_log.txt)

**Comment by mrdeep1** [comment]
Some initial comments - client side
````
v:1 t:CON c:GET i:5541 {} [ Uri-Path:/api/alarmclock, Request-Tag:0xd98d5601 ]
````
This should be really be on the wire
````
v:1 t:CON c:GET i:5541 {} [ Uri-Path:api, Uri-Path:alarmclock, Request-Tag:0xd98d5601 ]
````
Notice the separation of the path into different sections, each of which does not include the `/`.

The client needs to take the presented path `/api/alarmclock` and split it up using [coap_split_path(3)](https://libcoap.net/doc/reference/develop/man_coap_split_path.html) or [coap_path_into_optlist(3)](https://libcoap.net/doc/reference/develop/man_coap_path_into_optlist.html).  You may find it easier to use [coap_uri_into_optlist(3)](https://libcoap.net/doc/reference/develop/man_coap_uri_into_optlist.html) which then takes the parsed URI and splits it out into the appropriate CoAP options for sending over the wire.

For the server, to handle the `/api/alarmclock`, the definition line should be (note that the leading `/` is not there - if it was, then (correctly as it is CoAP legitimate to have a path such as `////` which is different from `/`) the resource that the client would need to request would be `//api/alarmclock`)
````
    resource = coap_resource_init(coap_make_str_const("api/alarmclock"), 0);
````
see [coap_resource_init(3)](https://libcoap.net/doc/reference/develop/man_coap_resource_init.html).

You are using a `2.03` response, which should only be used if there was an E-Tag option in the request and 2.03 is saying - "Unchanged".  I would expect you to be using a `2.05` response for a GET.  See [RFC7252 5.9.13 2.03 Valid](https://datatracker.ietf.org/doc/html/rfc7252#section-5.9.1.3)

For what I think is your actual issue.

You are creating a new PDU from with your server's request handler (or making use of the `response `PDU passed as a parameter to the request handler) and sending it off (as a CoAP CONfirmable message, with the client sending back the ACKnowledge message) using `coap_send()`.  The server should be responding with an ACK which happens on return from the request handler following the update of the response code within the request handler.  There is no need to do the `coap_send()` and this should not be done.  See [coap_register_request_handler(3)](https://libcoap.net/doc/reference/develop/man_coap_register_request_handler.html).

You are only sending 311 bytes across the wire, which is less than your MTU of 512.  So that is currently not an issue.

**Comment by safwansada** [comment]
@mrdeep1 : 
The issue involves @rakeshksahu trying to limit the **MTU size** to **512** bytes at the server end using the API function `coap_endpoint_set_default_mtu(ep, 512)`. 

However, when he attempts to send data from the server to the client that exceeds 512 bytes, using the following API:

`coap_add_data_large_response(resource,
                             session,
                             request,
                             response,
                             query,
                             COAP_MEDIATYPE_APPLICATION_CBOR,
                             0x2ffff,
                             0,
                             data, /* Size of data larger than MTU (512 bytes) after cbor conversion */
                             data,
                             nullptr,
                             nullptr);
coap_send(session, response);
`                                        
**After the CBOR conversion the size is more than 512 bytes.**

this is ther CBOR converted output "**<<. . k a l a r m D a y S e t . g a l a r m I d . i a l a r m T i m e e 0 0 : 0 0 m i s A l a r m A c t i v e . k i s R e c u r r i n g . d t y p e j A l a r m C l o c k . k a l a r m D a y S e t . . . . g a l a r m I d . i a l a r m T i m e e 1 1 : 4 5 m i s A l a r m A c t i v e . k i s R e c u r r i n g . d t y p e j A l a r m C l o c k . k a l a r m D a y S e t . g a l a r m I d . i a l a r m T i m e e 0 0 : 0 0 m i s A l a r m A c t i v e . k i s R e c u r r i n g . d t y p e j A l a r m C l o c k . k a l a r m D a y S e t . g a l a r m I d . i a l a r m T i m e e 0 0 : 0 0 m i s A l a r m A c t i v e . k i s R e c u r r i n g . d t y p e j A l a r m C l o c k . k a l a r m D a y S e t . g a l a r m I d . i a l a r m T i m e e 0 0 : 0 0 m i s A l a r m A c t i v e . k i s R e c u r r i n g . d t y p e j A l a r m C l o c k >>**"

with this, we encounters the error event **COAP_EVENT_XMIT_BLOCK_FAIL**. According to the log coap_dtls_Server.log, and the server is attempting to send the data multiple times with same error event.

If the MTU size is not restricted to 512 byte then we are not seeing this issue after if we send the data of larger size.

What is the solution for this after restricting the MTU size ?

**Comment by mrdeep1** [comment]
I am second guessing that when MTU is not restricted, the data fits into a single packet, and so the data does not need to be sent using multiple blocks using the CoAP Block2 option to split the overall payload.

The client is complaining about receiving the Block2 option of the first block and not asking for the next block so the server does not send all the blocks and eventually reports COAP_EVENT_XMIT_BLOCK_FAIL.

Why is the client complaining / getting confused?
Because you are initiating the send of the response packet from within the request handler rather than it getting sent by libcoap library after the return from the request handler call. The server logic in the request handler needs to be fixed.

The client confusion arises out of the response being CON, not ACK type of message.

If your intent is to do a separate (I.e. done sometime in the future) as opposed to a piggyback response, then the separate response must be done after the return from the request handler function.

You will have the same issue with your current logic if you try to sent a data size that is 1500 bytes or more without trying to reduce the MTU size.

My other comments need to be addressed as well in your code so that you are using the CoAP protocol as it is meant to be used.

**Comment by rakeshksahu** [comment]
Hello @mrdeep1,

 There were some issues in the code which are fixed now. Now I am not calling coap_send explicitly. I will be address the uri suggestions in a while.
Below are the description of changes.

- We were calling coap_pdu_init inside the request_handler to initialize the response instance.
- Also we are now setting coap_pdu_set_code for response to COAP_RESPONSE_CODE_CONTENT.

But we still see the same issue.
[client.txt](https://github.com/user-attachments/files/16391948/client.txt)
[server.txt](https://github.com/user-attachments/files/16391950/server.txt)

Do we need to send the data iteratively at server side if data length is more than max mtu size?

**Comment by mrdeep1** [comment]
The `response `PDU provided to the request handler is already correctly initialized with the appropriate type / token / message-id and any other pertinent CoAP options.  All that is needed in the response handler is to get the appropriate data, pass it to `coap_add_data_large_response()`,  call  `coap_pdu_set_code()` and then return from request handler.  You must not do a `coap_pdu_init()` on the response PDU or change the PDU type with `coap_pdu_set_type()` (it looks you are doing one of these).

See function `hnd_get_index()` or `hnd_get_example_data()` in `examples/coap-server.c`.

> Do we need to send the data iteratively at server side if data length is more than max mtu size?

Not if you have used `coap_add_data_large_response()` - libcoap handles things correcty.

**Comment by rakeshksahu** [comment]
We removed coap_pdu_init, and coap_pdu_set_type and let service take care of these. Additionally we have put 
```
coap_context_set_block_mode(
          m_coap_ctx, COAP_BLOCK_USE_LIBCOAP |
          COAP_BLOCK_TRY_Q_BLOCK | COAP_BLOCK_USE_M_Q_BLOCK);
```
earlier is was:
```
coap_context_set_block_mode(
          m_coap_ctx, COAP_BLOCK_USE_LIBCOAP | COAP_BLOCK_SINGLE_BODY);
``` 
to enable block mode transfer.
But with these we are still getting COAP_EVENT_XMIT_BLOCK_FAIL.
However, we see that client is receiving the data (attached logs). But transmission is happening multiple times.
Please let us know what needs to be fixed.
[client.txt](https://github.com/user-attachments/files/16413675/client.txt)
[dtls_server_block_send.txt](https://github.com/user-attachments/files/16413676/dtls_server_block_send.txt)

**Comment by mrdeep1** [comment]
Good that we are moving forward here.  Changing `coap_context_set_block_mode()` will not have an effect on the blocking mode issues you are having here.

Your server code is waiting for 1 second following a transmission before it receives the next response.  It is doing this consistently.
````
DAEMON.INFO: Jul 29 12:40:44.213 DEBG *  127.0.0.1:9909 <-> 127.0.0.1:34677 (if1) DTLS: netif: sent   60 bytes
DAEMON.INFO: Jul 29 12:40:45.216 DEBG *  127.0.0.1:9909 <-> 127.0.0.1:34677 (if1) DTLS: netif: recv  299 bytes
....
DAEMON.INFO: Jul 29 12:40:50.299 DEBG *  127.0.0.1:9909 <-> 127.0.0.1:34677 (if1) DTLS: netif: sent   61 bytes
DAEMON.INFO: Jul 29 12:40:51.300 DEBG *  127.0.0.1:9909 <-> 127.0.0.1:34677 (if1) DTLS: netif: recv   65 bytes
````
so there appears to be an issue with your `coap_io_process()` loop set up.  It is also possible that the client is adding in the 1 second delay between reads and writes over the network, not the server.

Does your host system properly support EPOLL?

It would be good to see the code block where `coap_io_process()` takes place for both the client and server. 

I think that this is now behind your COAP_EVENT_XMIT_BLOCK_FAIL as there are timeouts and packets get re-transmitted.

**Comment by rakeshksahu** [comment]
thanks for the insights, yes as per requirements we need to run coap_context with boost::asio::io_context, so we were running boost iocontext for 1 sec followed by coap context, which was causing the issue. Now we changed it to 200ms and it runs fine.

`
      while (true)
      {
        io_ctx.run_for(std::chrono::milliseconds(200));
        coap_server->runOnce();   // this calls coap_io_process
      }
`

**Comment by mrdeep1** [comment]
Thanks for the feedback.  Now, we have a 200ms delay after a packet (which includes DTLS negotiations) is sent before the response packet is read in for processing.

I have not investigated what boost::asio::io_context run_for actually does under the hood, but going with the current 200ms run period, I suggest that you have in your runOnce() function something like:-
````
  int max_time_ms = 100;
  while (max_time_ms > 0) {
     int ret = coap_io_process(ctx, max_time_ms);
     if (ret <= 0)
       break;
     max_time_ms -= ret;
  }
````
which then repeatedly calls coap_io_process() for up to 100 ms should there be any network traffic, else delays up to 100ms.  You will find that things run a lot faster.

**Comment by rakeshksahu** [comment]
sure will do it. Shall I close this issue then?

**Comment by mrdeep1** [comment]
The raised issue has now been addressed and resolved.  So please close this issue when you can.

I suggest you consider building libcoap as threadsafe (develop branch) and running the coap_io_process() in a separate thread with a default of, say, 1000ms wait time.

**Comment by rakeshksahu** [comment]
Sure, we are just waiting for a release tag. Once it is there we will migrate. :)
