### ISSUE TITLE
Instructions on implementing block mode in server side

### ISSUE THREAD

**Issue by rpb5bnc** [obgm/libcoap#287]
Our server application now needs to respond with payloads that exceed the MTU, so block mode is required.  Earlier last year it had been seen that there was not support for block mode in the server side of libcoap, and there had been a question raised about this.  The response at that time was that RFC7959 is not supported in libcoap, and the application layer must perform much of the block mode functionality.  Coming back now to the latest version of libcoap there is now the API function of coap_add_data_blocked_response().  There are four uses of this call now in the example server code, it appears the previous coap_add_data() calls have been changed over to this call.  At least one of these calls contains the comment "Invoke coap_add_data_blocked_response() to do all the hard work."  This comment along with only one call to this function in the example code gave the impression that block mode responses on the server were now addressed in libcoap through the use of this call.  There is another statement of "This function must only be called once per _pdu_."

When I first looked at the latest code and saw this new API and calls to it from the example code, I thought that this was all that was needed, to just change the call over from coap_add_data() to coap_add_data_blocked_response().  I see now that this is not the case and more logic is still needed at the application layer.  If that's correct, is there any example code, documentation, or some kind of instructions, that will explain how one would use this API call in sending back a response that exceeds the PDU size?  For example, there is that statement that this call must only be made once per PDU, but when the application handler is invoked it's invoked with a pointer to just this one PDU.  What are we to do after we make this first call in coap_add_data_blocked_response()?  How do we know how much data was sent, and how do we come up with a new PDU structure and set it up to continue on with the next block to be sent?  It's questions like these that I'm looking for answers to.

Thanks very much for all your work,
Pete

**Comment by mrdeep1** [comment]
What is not that clear in the documentation is that you provide to coap_add_data_blocked_response() the entire block of data (which will get split over several packets) that you want to send back to the client.

coap_add_data_blocked_response() then takes the appropriate fragment/slice out of this data block to put into the current PDU that is to be transmitted cased on the COAP BLOCK2 options provided by the client in the current packet request.

So, client requests data, server sends back the first fragment (saying this is a partial response), the client then acknowledges receipt of current fragment and requests the following fragment which the server sends back and so on. 

You simply need to respond to the client request, using the provided PDU and provide to coap_add_data_blocked_response() the entire data block who then does all the heavy lifting.  You do not create any additional PDUs, but can only respond once to an individual request (i.e use its PDU once).

I suggest that you also look at the man pages coap_pdu_setup(3), coap_handler(3) and coap_observe(3) for additional examples.

**Comment by rpb5bnc** [comment]
So if I understand what you are saying, our server application really does need to make just one call to coap_add_data_blocked_response(), passing in the entire payload to be sent and coap_add_data_blocked_response() does all the heavy lifting of fragmenting it up, building up the options, and sending each block/fragment in a packet as the client ACKs each of these packets.  If I have this correct, then this is awesome.  

I had just done a quick test where I adjusted the COAP_DEFAULT_MTU down to 256, knowing that my response payload was about 450 bytes.  What I saw at the client just one packet with 191 bytes of payload I immediately thought something was wrong.  And there *was* something wrong, the client most likely didn't do what it needed to do, that is ACK this first packet so that coap_add_data_blocked_response() could proceed with sending the next fragment/block.  I will dig deeper now that I understand this.  I guess I just assumed the worst when I saw what I saw and couldn't find an explicit statement of what was required at the server application level.  I began to think, "Uh oh, I have some code to write, and almost no time to get done."

Thanks again!

**Comment by mrdeep1** [comment]
Yes, your understanding is correct.  It is a simple replacement of coap_add_data() with coap_add_data_blocked_response() (with the whole data response) in the code to make GET work as expected at the server end.  It also adds in a ETAG option which is a hash of the entire block so that the client can detect if the block has changed (been dynamically refreshed etc.) during the chunked transfer.

The client does need to know to request the next block (See message_handler() in examples/client.c - COAP_OPT_BLOCK_MORE()).  I did think about putting the client side heavy lifting into a internal function, but then the handlers as registered by coap_register_response_handler() would need to pass back the aggregated data block which is too large to fit into a single PDU - so there would have to be an API change.

Likewise a PUT from a client to a server which the data has to be broken up could have new functions, but coap_register_handler() would have to be for a handler that provides the data as well as the PDU.  Another API change.

The following will transfer the autogen.sh file from the libcoap top level directory to the example server and transfer it back again - all blocked.

Server
````
$ coap-server -d10 -v9
````
Client (on same appliance - else different IP address)
````
$ coap-client -v9 -f autogen.sh -m PUT -b 1024 coap://127.0.0.1/example
$ coap-client -v9 -o /tmp/out coap://127.0.0.1/example
$ diff -Nau autogen.sh /tmp/out
````
You can try using the example coap-client against your server to check that all is OK

**Comment by rpb5bnc** [comment]
Excellent.  And thanks for the incantation for an example test.  This is a reasonably close test, too, because our scenario is a client sending in a Certificate Signing Request (CSR), the server taking it in, forwarding to a Certificate Authority, receiving back a new certificate for the client and sending it back to the client.  So in our case the client is sending in a payload and the server is sending back a payload, albeit a different payload but still, payloads in both directions.  One difference is that the higher layer protocol currently states that the POST method be used instead of PUT.  Not yet sure if that's an issue.  

Thanks again for libcoap and your guidance.
Pete

**Comment by rpb5bnc** [comment]
Ok, thanks.  I think I know what your saying here.  In our case, if the client were to repeat the enrollment request using POST, even if the CSR payload is identical, it's not guaranteed that the certificate in response will be identical.  Instead of sending back the previously created certificate, the response could be yet another new certificate with new "not_before" and "not_after" values and a new certificate index value, so it's ok that the POST is not idempotent.

**Comment by mrdeep1** [comment]
@rpb5bnc Is there anything else here that is needed, or can this be closed?

**Comment by ranjit4p** [comment]
@mrdeep1 What you have given is an example of using Block1 transmission. Can I get a sample for Block2 communication ?

**Comment by mrdeep1** [comment]
@rpb5bnc Sending the data to the coap-server uses Block 1, getting the data back from the coap-server is using Block 2.   With verbose logging enabled, you should see this.

**Comment by andygikling** [comment]
I'm also trying to use this.

My server handler gets called over and over again for each fragment.  The coap_add_data_blocked_response() does do what @mrdeep1 explained but how do I tell in the server code to, for example not load the file off of disk which I need to send back, on subsequent fragment calls to the handler?  

Is there an ID of some kind in the block transaction coming in from the client which the sever needs to hold on to in order to know that the call to the handler can be ignored and that the fragments are still in progress?

**Comment by mrdeep1** [comment]
@andygikling You can check on the server if there is a BLOCK2 request option.  If the block number is 0 and the More bit open the file, and then keep the file ptr open in some structure (e.g. in the user data ptr area of coap_session_t) until the BLOCK2 option comes in without the More bit set when things can get closed down.

You will need the ability to timeout the open file in case something happens with the client.  It may be that if there is a timeout, close the file ptr, and then re-open it when the next BLOCK2 comes in.

**Comment by andygikling** [comment]
@mrdeep1, that's perfect.  Thank you for clarifying. 
I'll post example handler code for this here or early next week so that you can close this issue.

**Comment by msandstedt** [comment]
@andy

**Comment by mrdeep1** [comment]
Agreed that coap_add_data_blocked_response() block handling logic can be replicated in the server application and then do the necessary fopen(), fseek() and fclose() every time the next fragment request comes in.

Also worth considering is mmap() to save a copy of the file into memory and maintaining the mmap() entry somewhere in the coap_session_t for the duration of the transfer (timeouts will need to be handled).

**Comment by andygikling** [comment]
We're interested in making it go as fast as possible, so I'd rather not fopen the file every time.  I wonder if Linux will do some caching under the hood which makes subsequent calls faster?

Hey @mrdeep1 on a related note, @msandstedt and I have been thinking about this more.  He points out that the library should probably use: 

COAP_RXBUFFER_SIZE 65507 /* maximum UDP payload */

instead of the current default of 1152 which assumes you're on a Ethernet network.  I understand it makes sense to be thrifty with memory when you're often running this stack on a small micro-controller.

Seems to me like COAP_DEFAULT_MTU, and the COAP_RXBUFFER_SIZE should be dynamic options of the library so one doesn't have to make patches or recompile when operating on gigabit networks for example.  

I imagine this has come up before but it might be good to drop a comment about the thought behind the decision.  It will certainly help future Googlers.

**Comment by mrdeep1** [comment]
I was not involved n the original design criteria for libcoap.  However https://tools.ietf.org/html/rfc7252#section-1 states
````
                                       Constrained networks such as
   6LoWPAN support the fragmentation of IPv6 packets into small link-
   layer frames; however, this causes significant reduction in packet
   delivery probability.  One design goal of CoAP has been to keep
   message overhead small, thus limiting the need for fragmentation.
````
and https://tools.ietf.org/html/rfc7252#section-4.6
````
                                            The CoAP specification
   itself provides only an upper bound to the message size.  Messages
   larger than an IP packet result in undesirable packet fragmentation.
   A CoAP message, appropriately encapsulated, SHOULD fit within a
   single IP packet (i.e., avoid IP fragmentation) and (by fitting into
   one UDP payload) obviously needs to fit within a single IP datagram.
````
so the current design is likely to be following that.  With the larger buffer sizes, there may be some stack limitations when the buffer is kept on the stack, and so `./configure --enable-small-stack` needs to be enabled.  The underlying IP stack will also need to need buffers to handle packet re-assembly.

For performance, if mmap() is available, the entire file is mapped into virtual space and then the underlying O/S can handle all the page load requirements for the file as it is sent back in CoAP BLOCKS.

**Comment by mrdeep1** [comment]
#554 (not yet merged) is likely to give the flexibility needed here as well as having additional documentation.

**Comment by mrdeep1** [comment]
#554 is now in the develop branch.  It is now possible to instruct libcoap (set COAP_BLOCK_SINGLE_BODY) to assemble all the payloads of a body and just present the body to the server for processing, and then for the server to give a large body to libcoap who will then send all of the individual payloads to the client - and on successful transmission (or failure) a callback to free off the body if needed.  So, from the server's perspective, it is a single 'read' and a single 'write' with possible completed callback.

**Comment by obgm** [comment]
Closed off as answered/resolved.
