### ISSUE TITLE
Questions on APIs in coap_dtls.h 

### ISSUE THREAD

**Issue by jitin17** [obgm/libcoap#346]
I am trying to add support for DTLS using mbedtls in `libcoap`, and this requires implementing APIs given in `coap_dtls.h`. 

I have reached a stage where the handshake between coaps server and coaps client  is successful, but fails in the subsequent actions.

I think the problem is in the implementation of `coap_dtls_is_context_timeout()`, `coap_dtls_get_context_timeout()`, `coap_dtls_get_context_timeout()` found in `coap_dlts.h`, I find the documentation of these APIs to less useful. Can someone shed light on what should these functions do if mbedtls is being used?

**Comment by mrdeep1** [comment]
Hi @jitin17. It is good to see that an attempt to provide mbedTLS support for libcoap.

I do not think that coap_dtls_is_context_timeout() and coap_dtls_get_context_timeout() will be causing you major issues - this is just used to determine from the underlying (D)TLS layer when the next (internal to (D)TLS) retransmit of data is required if the required response packet has not come back for the previous transmit (in case a UDP packet has got lost).

I assume that you are testing a non mbedTLS client against a mbedTLS server or vice versa?
The non mbedTLS application may be able to give you a clue as to what is failing with full debugging enabled.

I also assume that you are running with the latest code from the develop branch.

GnuTLS currently works fine with coap_dtls_is_context_timeout()returning 1 and coap_dtls_get_context_timeout() returning 0 which disables any determination of retry timeouts at the (D)TLS layer - but that may need to be fixed.

If the (D)TLS layer setup has been completely successful, but no (encrypted) data is being sent back and forth and your are trying with a mbedTLS server, then I would check that coap_read_endpoint() when it calls coap_handle_dgram_for_proto() causes coap_session_new_dtls_session() to have been called otherwise data will not flow.

**Comment by jitin17** [comment]
@mrdeep1 Would you mind sharing your email id address so that I can share logs and other info with you?

**Comment by mrdeep1** [comment]
See https://sourceforge.net/p/libcoap/mailman/message/36656100/ for my email address from my posting.
