### ISSUE TITLE
Can function get_common_name_from_cert() return many present identifiers of the certificate?

### ISSUE THREAD

**Issue by lieunguyen-tma** [obgm/libcoap#354]
Hi all,

Could you please to help me answer the question below:

Example:
- The client's certificate has the reference identifier list: "client.sample.example.com", "sample1.example.com", "_xampp.example.com".

- The server's certificate has three identifiers: Subject CommonName(CN-ID: "server.sample.example.com"),  Subject Alternative Name (DNS-ID: "sample2.example.com", SRV-ID: "_xampp.example.com").

When the libcoap does function get_common_name_from_cert()of the server's certificate, it only return one present identifier ("sample2.example.com"), this identifier is not matching with any of the reference identifiers. But the server's certificate contains another present identifier ("_xampp.example.com") that can match with a reference identifier ("_xampp.example.com").

Can function get_common_name_from_cert() return many present identifiers of the certificate?
Is there any others function that can get all identifiers in the certificate?

Thanks
Lieu Nguyen

**Comment by mrdeep1** [comment]
@lieunguyen-tma The simple answer is no.  This function (could be better named) abstracts the Subject Alternative Name (SAN) if available (based on the DNS entry), and if the SAN is not available it then abstracts the CN= (Common Name) entry and returns the result of the findings.  So, for the server certificate, it is correctly returning "sample2.example.com".  I have renamed the function in PR #355 

This function does not look for an common entry between 2 certificates.  If you are interested in mutual authentication, then to do this only based on a common name entry between the 2 certificates can be unsafe.  Cert # 1 can be generated by CA # 1 and Cert # 2 can be faked by a bad CA # 2.  Both certificates need to be generated by the same CA so that the applications using the 2 certificates can trust each other before adding in additional checks such as the server returns a certificate with the same SAN/CN as the client is trying to connect to.

If you are using the coap_dtls_cn_callback_t validate_cn_call_back; defined in coap_dtls_pki_t, then as per
````
typedef int (*coap_dtls_cn_callback_t)(const char *cn,
             const uint8_t *asn1_public_cert,
             size_t asn1_length,
             struct coap_session_t *coap_session,
             unsigned depth,
             int validated,
             void *arg);
````
the whole of the certificate is passed to the call back function in ASN1(DER) format, so your application can abstract all the different names that you want it to.

**Comment by lieunguyen-tma** [comment]
Dear Mr. @mrdeep1,

Thank you for replying me. Your answer helped me solve the problem.

Thanks
Lieu Nguyen

**Comment by mrdeep1** [comment]
@lieunguyen-tma Glad to be of service.  Please close this issue if there are no further questions on this subject.

**Comment by lieunguyen-tma** [comment]
There is no problems in this issue.
Closed the issue.
