### ISSUE TITLE
coap_split_uri should operate on const str

### ISSUE THREAD

**Issue by chrysn** [obgm/libcoap#37]
The coap_split_uri function modifies the hostname to lowercase. While this is documented, it is impractical when dealing with URIs that come along as `const char`, be it from ROM or from network traffic.

Depending on the API guarantees currently in place, I'd prefer the function to just drop that behavior and take a `const` argument (`*p` and `*q` would become `const` too); if that's impossible, there should be a `coap_split_uri_const` or similar function that does provide said behavior.

I'd argue that lowercasing the hostname is a behavior that's pointless, because even when lowercased, there can still be different string representations of what is an equivalent network destination, be it before DNS resolution ("github.com" and "github.com." should be equivalent), or after (alias hostnames). Hashing the hostname only takes you so far, and if a system does encounter the same hostname in different capitalizations, it should be able to cope with it just as if they were denormalized in any other way. The systems' `getaddrinfo` and friends should all be able to cope with mixed-case names.

**Comment by obgm** [comment]
The short answer is: I have no strong opinion on this and do not object in dropping the normalization. Please check commit cb6d3c4 if it does the right thing for you.

The long answer is: I agree that for constrained devices, it might be more useful to drop the normalization in favor of being able to pass strings from ROM (in contrast to strings from the network as the normalization is done here exactly for that purpose). Your argument that "there can still be different string representations of what is an equivalent network destination" is not relevant here as coap_split_uri() deals with the host part of a URI (cf. RFC 3986), not with DNS names. The canonical form of the host part is lowercase, and that's why coap_split_uri() has transformed it as a convenient service for applications that want to provide virtual hosts.

**Comment by chrysn** [comment]
> Please check commit cb6d3c4 if it does the right thing for you.

Thanks, yes, things work now with ROM too.
