### ISSUE TITLE
about pdu management process, Is there a memory leak?

### ISSUE THREAD

**Issue by yr2004** [obgm/libcoap#385]
1、when we want  to send a coap msg, we need to request a new pdu
2、the size of pdu is about 264+32
3、when the coap msg type is not NON confirmable msg, it will delete pdu, until it receives the ack form the server.
4、so the question is that, if the server not ack the client, and the client still sent msg, Is there a memory leak?

**Comment by obgm** [comment]
There shouldn't be a memory leak but you can check using valgrind.

**Comment by mrdeep1** [comment]
@yr2004 Have you been able to confirm that there actually is a memory leak?
Certainly once the Confirmable logic has retried (default 4 times) sending the packet, the pdu will get deleted, but there could be a bug elsewhere.

**Comment by mrdeep1** [comment]
@yr2004 Please confirm whether this is a real issue or not.  If not, then can you close this please.

**Comment by yr2004** [comment]
close it
   
 
 
 

 ------------------ 原始邮件 ------------------
  发件人: "mrdeep1"<notifications@github.com>;
 发送时间: 2019年9月18日(星期三) 下午5:35
 收件人: "obgm/libcoap"<libcoap@noreply.github.com>;
 抄送: "明天"<yr97@foxmail.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [obgm/libcoap] about pdu management process, Is there a memoryleak? (#385)

 

 
@yr2004 Please confirm whether this is a real issue or not. If not, then can you close this please.

**Comment by fbucafusco** [comment]
Hi !
I am re-opening this because I have a similar issue with a "memory leak" that I am experiencing. 
I have an application that sent 2 type of COAP_MESSAGE_CON. Everything goes well until I decided to change one of the to be a COAP_MESSAGE_NON. 
For this NON msg I am not waiting a response, so I dont call cop_io_process. 
I just only  call coap_send.
I have the libcoap usage in a class, but my code is something like this:

```
coap_pdu_t *pdu = this->pdu_create( payload , payloadsize ,  path , msg_type);  //msg_type has the info if COAP_MESSAGE_NON or not and that the rqst is a POST- calls coap_new_pdu
coap_send(this->m_session, pdu );
```

When I configure the message as COAP_MESSAGE_CON and (after the code I copied) wait for a repsonse, the leak is not there. But configuring it as NON, the leak appears. 

I am using the ESP32 with ESPIDF framework and I am measuring the leak using `esp_get_free_heap_size() `before and after the "send receive" operation.

I tried to track the leak and discard if I was messing it, but as far I can tell, I did things right. 

Any help will be appreciated.

**Comment by mrdeep1** [comment]
@fbucafusco It would really be appreciated if you created a new issue as this issue was closed getting on for 3 years ago and a lot has changed in both libcoap and esp-idf code since then. 

When raising a new issue, it will prompt you for further background information which would be helpful for troubleshooting here.
