### ISSUE TITLE
running the coap-client from java

### ISSUE THREAD

**Issue by rvjansen** [obgm/libcoap#421]
From java it is possible to run a program in a thread and get to its input- and outputstreams. This approach fails with coap-client. When I run coap-client (in this case to the IKEA Trådfri zigbee gateway), it seems that the calling class receives a line on stderr, and an answer on stdout.
It hangs on InputStream.read() (or BufferedInputStream.readLine(). However many times I retry, the output never becomes available.

Now when I use a small brexx script (and I imagine probably also when I use bash) this problem does not happen, and I can receive both the stderr and stdout answers, with the same java invocation.

As I
(1) would like to use this without the rexx script
(2) maintain both the NetRexx and Pipelines compilers who fail on this call
(3) coap-client is the only executable that ever failed on this call

I would like to ask you if you have some idea as to why this happens.
For completeness, this is my NetRexx code that calls the native executable:

 /**
   * Method outtrap starts an OS process from a command line in an ArrayList
   * @param command is a List that has the command to be executed as elements
   * @return List containing the output of the command
   */
  method outtrap(command_=ArrayList) returns ArrayList
    this.commandList = command_
    do
      pb = ProcessBuilder(command_)
      pb.redirectErrorStream(1)
      this.pid = pb.start()
      in = BufferedReader(InputStreamReader(this.pid.getInputStream()))
      line = Rexx in.readLine()
      loop while line <> null
	this.outList.add(line)
	line = Rexx in.readLine()
      end
      pid.waitFor()
      returncode = pid.exitValue()
      return this.outList
    catch iox=IOException
      say iox.getMessage()
      return ArrayList()
    catch InterruptedException
      say "interrupted"
      return ArrayList()
    end -- do

I left out all the wait for read() stream code, because the scripted version does not need them.

Many thanks in advance.

**Comment by mrdeep1** [comment]
The coap-client will only ever read from `stdin` if the `'-f -'` option is used.  Otherwise it is driven by the run-time options on the command line (Note the `in` of `stdin` which means executable is only expecting input).  InputStream.read() in the Java application will never receive anything from the executed executable.

The coap-clent will write information sent from the CoAP Server on `stdout` and if any errors are detected, then these errors will be written out on `stderr`.

Furthermore, if logging is enabled, depending on the level of severity, information will be written to `stdout` or `stderr` as appropriate.

So, in your Java application, reading from `stdin `makes no sense (but writing to it may) - your Jave code needs to read from both `stdout `and `stderr `- perhaps differentiating between normal output and errors when reporting the information.

See for example https://stackoverflow.com/questions/38764548/launching-external-process-from-java-stdout-and-stderr

**Comment by rvjansen** [comment]
Thanks mrdeep1, but this:
pb.redirectErrorStream(1)
this.pid = pb.start()
in = BufferedReader(InputStreamReader(this.pid.getInputStream()))

does in fact read from a combined stderr and stdout, it is somewhat confusingly named, but blame the Java team here. The stdin is fed from an arraylist, this all works. Well, for every other executable I ever used.

It seems the coap-client executable does not block on output, I'll put a trace in it to see what happens here. I appreciate that something asynchronous is turned into something synchronous, but the way it is done seems to be throwing off the - at least 20 years old way - java expects it. When wrapping it in a script, and calling that, it works. I'll report back when I know what does it, I just thought someone could give me a quick hint.

**Comment by mrdeep1** [comment]
coap-client used the stdio library (fprintf(), fwrite() etc) which is buffered output except when outputting to a tty device (not the case here when writing over a pipe to a wrapper application).

You may want to sprinkle the coap-client code in appropriate places with fflush() calls to force the buffered I/O to flush out its internal buffers.  Otherwise, these internal buffers will only get flushed out when full, or possibly when coap-client exits.

**Comment by rvjansen** [comment]
Coming back to this, it turned out that leaving out single quotes on the latter part of the argument caused this behaviour. Reluctant to call it a bug, I'll leave it at that.
