### ISSUE TITLE
dtls branch has issue with ELF

### ISSUE THREAD

**Issue by anupam19** [obgm/libcoap#45]
Got this error when tried to compile in raspbian in RPi

```C
cc -Wall -std=c99 -pedantic -g -DTEST_INCLUDE -DDTLSv12 -DWITH_SHA256   testecc.c ecc_test.o test_helper.o   -o testecc
/usr/bin/ld: ecc_test.o: Relocations in generic ELF (EM: 3)
/usr/bin/ld: ecc_test.o: Relocations in generic ELF (EM: 3)
/usr/bin/ld: ecc_test.o: Relocations in generic ELF (EM: 3)
/usr/bin/ld: ecc_test.o: Relocations in generic ELF (EM: 3)
/usr/bin/ld: ecc_test.o: Relocations in generic ELF (EM: 3)
/usr/bin/ld: ecc_test.o: Relocations in generic ELF (EM: 3)
ecc_test.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'testecc' failed
make[3]: *** [testecc] Error 1
```
Please look at this issue

**Comment by tijuca** [comment]
Please post a complete log about what you have done, I (and others) can't follow what happen. And if the issue is left due a proper clean up, as suggested by Olaf in private email, than please close the report.

And I can strongly suggest to post such problems on the mailing list, there are more people than the repository owner get informed. GitHub isn't good place to discuss such things.

**Comment by anupam19** [comment]
Worked. closing
