### ISSUE TITLE
What is the changlog for 4.2.1?

### ISSUE THREAD

**Issue by luminais** [obgm/libcoap#516]

**Comment by obgm** [comment]
The [announcement](https://sourceforge.net/p/libcoap/mailman/message/36801445/) briefly lists the major changes. The [roadmap document](https://libcoap.net/roadmap.html) also gives an overview of changes in major versions. Releases with changes in minor version number usually are only bugfix releases with small visible changes. Since the advent of platforms such as [Github](/) it has become very easy to trace the detailed changes of software as the entire development process and the commit history is made transparent.
