### ISSUE TITLE
How to support mbedtls in libcoap?

### ISSUE THREAD

**Issue by WEN-XUE** [obgm/libcoap#594]
Excuse me, I'm a student from Taiwan.
 I want to set a network environment which use CoAP and MbedTLS library, and i find that libcoap can support Mbedtls for only DTLS now. 
**But I don't know how to set it.**
i clone your project libcoap, and executed command **"./configure --enable-dtls --with-mbedtls".** and then i got this error "**You want to build libcoap with DTLS support by the mbed TLS library but library 'mbedtls' could not be found!".**
So I copied the mbedtls project to the local folder **"libcoap/ext"** from github and tried again. The result was **the same error message.**
What should I do to be correct?
Thank you！

**Comment by obgm** [comment]
You most likely need to install the package `libmbedtls-dev` on your system.
If you want to do from scratch, you can build mbedtls and install it to some place on your system. (Remember to set the include path and library path and possibly the run path properly if that is not one the default search locations on your system.)

**Comment by WEN-XUE** [comment]
Hi obgm, thank you for your help.
I installed the package libmbedtls-dev on my system and executed command "**./configure --enable-dtls --with-mbedtls --disable-documentation**", and the result looked normal.  

The result log is shown below:
------------------------------------------------------------------------------------
libcoap configuration summary:
      libcoap package version : "4.3.0beta"
      libcoap library version : "2.1.0"
      libcoap API version     : "2"
      libcoap DTLS lib extn   : "-mbedtls"
      host system             : "x86_64-pc-linux-gnu"
      build with TCP support  : "yes"
      build DTLS support      : "yes"
         -->  mbed TLS around : "yes" (found mbed TLS)
              MBEDTLS_CFLAGS  : ""
              MBEDTLS_LIBS    : "-lmbedtls -lmbedcrypto -lmbedx509"
      build using epoll       : "yes"
      enable small stack size : "no"
      build doxygen pages     : "no"
      build man pages         : "no"
      build unit test binary  : "no"
      build examples          : "yes"
      build with gcov support : "no"
      build shared library    : "yes"
      build static library    : "yes"
------------------------------------------------------------------------------------

But when I enter the command make, I will get the following error message
and I can’t find any structure named **bedtls_x509_crt** in the libcoap folder.
I see that this structure name is defined in the x509_crt.h file of mbedtls on github.
Should I go to clone the mbedtls project to the local folder libcoap/ext?

------------------------------------------------------------------------------------
  CC       src/libcoap_2-mbedtls_la-coap_mbedtls.lo
src/coap_mbedtls.c:94:3: error: unknown type name ‘mbedtls_x509_crt’
   mbedtls_x509_crt cacert;
   ^
src/coap_mbedtls.c:95:3: error: unknown type name ‘mbedtls_x509_crt’
   mbedtls_x509_crt public_cert;
   ^
src/coap_mbedtls.c:109:3: error: unknown type name ‘mbedtls_x509_crt’
   mbedtls_x509_crt cacert;
   ^
src/coap_mbedtls.c:110:3: error: unknown type name ‘mbedtls_x509_crt’
   mbedtls_x509_crt public_cert;
   ^
src/coap_mbedtls.c:255:25: error: unknown type name ‘mbedtls_x509_crt’
 get_san_or_cn_from_cert(mbedtls_x509_crt *crt)
                         ^
src/coap_mbedtls.c:296:42: error: unknown type name ‘mbedtls_x509_crt’
 cert_verify_callback_mbedtls(void *data, mbedtls_x509_crt *crt,
                                          ^
src/coap_mbedtls.c:420:23: error: unknown type name ‘mbedtls_x509_crt’
 setup_pki_credentials(mbedtls_x509_crt *cacert,
                       ^
src/coap_mbedtls.c:421:23: error: unknown type name ‘mbedtls_x509_crt’
                       mbedtls_x509_crt *public_cert,
                       ^
--------------------------------------------------------------------------------------

My environment is using ubuntu16.04.
My steps are as follows
1. sudo apt-get install libmbedtls-dev.
2. git clone this libcoap project.
3. cd libcoap  and run ./autogen.sh.
4. run ./configure --enable-dtls --with-mbedtls --disable-documentation.
5. make.

Thank you！

**Comment by mrdeep1** [comment]
No, you do not want to pull in the mbedtls project into libcoap/ext as that will not make any difference and libcoap is not setup to use that for Mbed TLS.

I am wondering if you have 2 sets of include/mbedtls files in different directories and there is confusion as to which one should be used when compiling the code.

The libcoap Mbed TLS support includes the file `<mbedtls/ssl.h>` in `src/coap_mbedtls.c`.   `<mbedtls/ssl.h>` then includes `<x509_crt.h>` if the conditional variable `MBEDTLS_X509_CRT_PARSE_C` is defined.  `MBEDTLS_X509_CRT_PARSE_C `normally is defined in` "config.h"`.

Please check and confirm that `include/mbedtls/config.h` has `MBEDTLS_X509_CRT_PARSE_C `defined and confirm the files mentioned in the previous paragraph do contain the information as presented.

The github libcoap build system uses Ubuntu 18.04.05 UTS which works fine.

**Comment by champoms** [comment]
env: Ubuntu core 16.

I also try to use mbedtls library with libcoap and i have followed the same steps as @WEN-XUE  except that I downloaded "https://github.com/ARMmbed/mbedtls/tree/development/include/mbedtls" this directory and put it into the libcoap directory before making the make command. (because there was apparently some .h missing)

Here is the error that I had:

`ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/champignon/libcoap'
Making all in man
make[2]: Entering directory '/home/champignon/libcoap/man'
  CC       examples-code-check.o
  CCLD     examples-code-check
make[2]: Leaving directory '/home/champignon/libcoap/man'
Making all in tests
make[2]: Entering directory '/home/champignon/libcoap/tests'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/champignon/libcoap/tests'
Making all in examples
make[2]: Entering directory '/home/champignon/libcoap/examples'
  CC       client.o
  CCLD     coap-client
../.libs/libcoap-2-mbedtls.so: undefined reference to `mbedtls_sha256_update_ret'
../.libs/libcoap-2-mbedtls.so: undefined reference to `mbedtls_sha256_starts_ret'
../.libs/libcoap-2-mbedtls.so: undefined reference to `mbedtls_sha256_finish_ret'
../.libs/libcoap-2-mbedtls.so: undefined reference to `mbedtls_ssl_set_mtu'
collect2: error: ld returned 1 exit status
Makefile:477: recipe for target 'coap-client' failed
make[2]: *** [coap-client] Error 1
make[2]: Leaving directory '/home/champignon/libcoap/examples'
Makefile:1113: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/champignon/libcoap'
Makefile:650: recipe for target 'all' failed
make: *** [all] Error 2
`
Hope you will be able to help.

Thanks in advance.

**Comment by mrdeep1** [comment]
> I downloaded "https://github.com/ARMmbed/mbedtls/tree/development/include/mbedtls" this directory and put it into the libcoap directory before making the make command. (because there was apparently some .h missing)

This really worries me that you had to do this because of some missing .h files - the MbedTLS include files should not be libcoap directory at all and is a recipe for failures in the future whenever Mbed TLS library code gets updated.  It maybe that you need to use the CPPFLAGS on the ./configure line (see ./configure --help).

If you are cloning mbedtls, then it needs to be built in that cloned tree and installed before being used by libcoap.

mbedtls_sha256_update_ret() was added to MbedTLS 2.7.0.  The minimum required version for MbedTLS is 2.7.10 and it looks like you are using an older library to link against (but using the later header files - which is not a good move).

**Comment by champoms** [comment]
Ok I managed to make it works !

Here is what I made :

(delete previous installation)
sudo apt-get install libmbedtls-dev.
git clone this libcoap project
cd libcoap 
git checkout master
./autogen.sh
run ./configure  --with-mbedtls --disable-documentation
make

**Comment by mrdeep1** [comment]
Interesting.  The master branch does not include `mbedtls`, so the option `--with-mbedtls` is being silently ignored in your build.  You are building with another SSL library (probably GnuTLS).

You need to checkout `develop `and build again.

**Comment by WEN-XUE** [comment]
Hi @mrdeep1, thank you for your help.
Hi @champoms , thank you for trying to solve my problem.

I changed my ubuntu version to 18.04 LTS and retryed the steps of my second reply. The result was successful.
And i used the example of this project into two terminals to simulate the server side and the client side.  The result was successful too.
I guess the version of mbedtls installed on ubuntu16.04 is too low, so let it fails. 
But I am not sure, because I cannot find the version of mbedtls used by libmbedtls-dev. (in ubun16.04)

The following are my test steps and I hope it can be provided to people in need for reference.

My environment is using **ubuntu18.04**.
My steps are as follows

"sudo apt-get install libmbedtls-dev"
git clone this libcoap project.
"cd libcoap" and run "./autogen.sh"
run "./configure --enable-dtls --with-mbedtls --disable-documentation"
make.

open two terminal of linux
one is server and the other is client.
server:
"cd libcoap/example"
run "./coap-server -k 1234 -v9"

client:
"cd libcoap/example"
run "./coap-client coaps://[127.0.0.1]/time -k 1234 -u CoAP -v9"

I also used wireshark to capture packets and it seems that there is a normal handshake.
The results of capturing packets can refer to the following
server                   client
                             client hello
<------------------ 
hello verify request
------------------>
                             client hello
<------------------ 
server hello
server key exchange
server hello done
------------------>
                             client key exchange
                             change cipher spec
                             encrypted handshake message
<------------------
change cipher spec
encrypted handshake message
------------------>
                             application data
<------------------
application data
------------------>

**Comment by mrdeep1** [comment]
The Mbed TLS version can be found in `include/mbedtls/version.h` and the definition is `MBEDTLS_VERSION_STRING`.

**Comment by WEN-XUE** [comment]
Hi @mrdeep1 ,
OK I got it and I checked the mbedtls version used by the two packages libmbedtls-dev 
(one is ubuntu18.04 and the other is ubuntu16.04)
The version of mbedtls in ubuntu18.04 is mbedtls 2.8.0
The version of mbedtls in ubuntu16.04 is mbedtls 2.2.1
So the reason for the previous failure is that the version of mbedtls is lower than 2.7.10.
Now i know it, thank you very much for your help！

Record it for myself
After installing the libmbedtls-dev package, can find the mbedtls version in **/usr/**include/mbedtls/version.h

**Comment by mrdeep1** [comment]
Hi @WEN-XUE .  The develop branch has been updated with #598 which now checks that Mbed TLS library is of a recent enough version for it to be used in a libcoap build.  It now tells you that using version 2.2.1 (Ubuntu 16.04) s insufficient to continue building libcoap code.

Please close off this Issue if you are happy with the above.

**Comment by WEN-XUE** [comment]
hi @mrdeep1 , OK! Thanks you！

**Comment by WEN-XUE** [comment]
Hi all,
I have another related question.
I want to change the ciphersuite of mbedtls in libcoap, but i don't know how to do it.

If i download the mbedtls library from github repository and want to change ciphersuite that i can change the macro of config.h file to select ciphersuite.

But this method is useless for mbedtls in libcoap.
I think it is because the library file of mbedtls in libcoap has not been changed, although I changed the macro in the config.h file.

Hope somebody will be able to help me.
Thanks in advance.

**Comment by obgm** [comment]
Hi @WEN-XUE please open a new issue for this question as many people most likely wont notice this (merely unrelated) follow-up on an already closed issue.

**Comment by WEN-XUE** [comment]
Hi obgm,
OK, thank you.
