### ISSUE TITLE
valgrind - short cut / how to

### ISSUE THREAD

**Issue by boaks** [obgm/libcoap#616]
I would like to apply more integrity checks when running libcoap's server and client in interoperability tests with Eclipse/Californium. One option seems to use valgrind for that. Several other issues here refer to that. Though I'm focused the past time more on Java than C, I'm not common to the use of valgrind.

Is there a "short cut" or "how to" for libcoap? Especially with dtls enabled?
Or is the "way to go" to read the valgrind docu and search for tutorials there?

(By the way, I prefer for Californium issues instead of the mailing list. Just in the case that for libcoap the mailing list is preferred, let me know.)

**Comment by mrdeep1** [comment]
Yes, `valgrind `is extremely useful (for both (D)TLS and no encryption).  There is no libcoap howto per se,  You just need to make sure that at exit of a program there is a clean-up / de-allocate of expected information otherwise `valgrind `reports lots of allocated information.  This is done in the examples by trapping `SIGINT `and then clearing up based on the `quit `flag in the main loop.  `atexit()` is an alternative.

An example of where the libcoap build uses `valgrind `is `.github/workflows/main.yml` . 

A potential gotcha is that when making the examples, for example `examples/coap-server`, `examples/coap-server` can end up as a script that invokes the binary executable `examples/.libs/coap-server`.  You need to valgrind the binary executable.  The use of `libtool `can work whether `.libs` should be added to the path or not.

I tend to use
````
valgrind --track-origins=yes --leak-check=yes --show-reachable=yes executable <executable_options>
````
Some libraries have information leaks / memory usage inconsistencies and if confirmed that they are issues with the library, these can be suppressed with the valgrind `--suppressions=<suppression_file>` option.  The format of `suppression_file `is complex and beyond the scope of this response (see `tests/valgrind_suppression`).

**Comment by obgm** [comment]
Regarding your question about GH issues vs. mailing list: Both are okay. Since the project has been moved to GitHub, most people have adapted to the GitHub workflow hence using its Issue tracker and PR submission tool, and the mailing list has become very quiet (but still responsive). Therefore, it is perfectly okay to use any of the two options you like best.

**Comment by boaks** [comment]
Thanks!
