### ISSUE TITLE
adding libcoap to eclipse IDE (CDT) on ubuntu

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#626]
hello,
i dont know if i should be posting this here or not, am still a beginner and dont know much, but am welling to learn.
i searched for many tutorials on ow to add libraries to **eclipse ide** but none seems to work with me , i am pretty sure that am doing something wrong.
what i want to know is after installing the libcoap library on ubuntu, how can i link the GCC compiler to the library's files and which files are those.

thanks in advance.

**Comment by mrdeep1** [comment]
@flukkyy I am not familiar with the Eclipse IDE, but I would be expecting that (assuming you built and installed libcoap using the default installation locations) that you need to add in the include directory` /usr/local/include` (assuming you are using the latest code in the develop branch, otherwise it could be `/usr/local/include/coap` or `/usr/local/include/coap2`) and that the library directory includes `/usr/local/lib`.  The library name to link with is dependent on which TLS library you compiled libcoap for, but is likely to be one of -lcoap-2, -lcoap-2-gnutls, -lcoap-2-openssl, -lcoap-2-mbedtls or -lcoap-2-tinydtls .

Any application code will need #include `<coap2/coap.h>` to pull in the libcoap header files.

**Comment by flukkyy** [comment]
@mrdeep1 thank you for the response sir! i tried what you said and it worked i was linking to wrong library names..

i have another question, if i want to use the source code of the library, copying the .h and .c files is enough or i need some other files that needs to be added to the project ?
to make it more understandable; i am trying to create a project to be implemented in a gateway and using the libcoap functions to assure sending/receiving data to/from the server.

**Comment by mrdeep1** [comment]
To be able to rebuild the libcoap library, you will certainly need more the *.c and *h files.  The other files needed are totally dependent on the build environment you will be using.  Just copying files is likely to have downstream issues when libcoap library code has any fixes that need to be merged in.

I am not sure why you cannot just have the appropriate libcoap libraries pre-built and installed on your gateway.  Then you just need to focus on getting the application gateway up and running.  I need to remind you that libcoap is not currently multi-thread safe.

**Comment by flukkyy** [comment]
hello @mrdeep1, if you don't mind can you please tell me more about the other files needed, because tried compiling with every*.c and *.h file i saw necessary but i am stuck and can't compile the project.
i am using this method instead of installing the library on the gateway to allow us to bring modifications if needed to the files in future.

**Comment by mrdeep1** [comment]
For the libcoap library, you will need to compile all the files in `src/*.c` with all the `include/coap2/*.h` available. ` include/coap2/coap.h` is a built file by the libcoap build environment with all the code versions etc., and probably can be used as is. ` ./coap_config.h` is created when you run` ./configure` in the normal libcoap build environment and describes what options / header files are to be used when compiling the `src/*.c` files.  You may need to modify ` ./coap_config.h` if there are compilation errors.

How you go beyond that point (e.g. to create the libcoap library and link it to your source code) with your IDE, I have no idea.

**Comment by flukkyy** [comment]
i tried everything you said and of course a found a bunch of errors, after searching and reading the issues and fixes i stomped on this error that i couldn't fix in file coap_asn1_internal.h. the error in line 68 says: " expected ‘,’ or ‘...’ before ‘class’ ". can you help me with this one. thanks.

another thing i want to know, as far as i can see there is a lot of changes going on with the library's current version like the message_id and all.. is it better for me to try and work with another version of libcoap.?

**Comment by mrdeep1** [comment]
I wonder if there is confusion somewhere with the variable name `class `- change it to `tagclass` and see if that fixes your issue.  Otherwise, I have no idea what it is complaining about.

Yes, libcoap `develop `branch is is a state of flux, but will shortly be released as version 4.3.0.  It all depends on what functionality within libcoap that you are looking for when deciding which version to settle on.  There certainly has been a lot of changes since 4.2.1 (released Nov 2019).  There is not a changes file detailing the changes though.

**Comment by flukkyy** [comment]
Well the `tagclass` didn't solve my issue but will try and search more.
For the functionality am looking for, i just wanna send and receive data stored in *.xml files under a secure connection.
