### ISSUE TITLE
How to change the ciphersuite of mbedtls in libcoap?

### ISSUE THREAD

**Issue by WEN-XUE** [obgm/libcoap#632]
Hi all,
I want to change the ciphersuite of mbedtls in libcoap, but i don't know how to do it.

If i download the mbedtls library from github repository and want to change ciphersuite that i can change the macro of config.h file to select ciphersuite.

But this method is useless for mbedtls in libcoap.
I think it is because the library file of mbedtls in libcoap has not been changed, although I changed the macro in the config.h file.

Hope somebody will be able to help me.
Thanks in advance.

**Comment by mrdeep1** [comment]
@WEN-XUE The` include/mbedtls/config.h` is used to control how the Mbed TLS library is built and what functionality that library contains.  ` include/mbedtls/config.h` should not be updated without rebuilding Mbed TLS, otherwise the contents / functionality of the Mbed TLS library will potentially give you unexpected link / runtime errors.

It is true that libcoap includes` mbedtls/config.h` through `mbedtls/version.h`  but cannot be used to control the available cipher suites - what is available is what the Mbed TLS library gives you.

The function `set_ciphersuites() `in `src/coap_mbedtls.c `is used to abstract all the known ciphers, filter some out by not being strong enough, sorting into PKI / PSK support and then builds a list of ciphers that can be subsequently negotiated.

For libcoap, you can only use one of the cipher suites that are available from MbedTLS library - not add in a new one.

**Comment by WEN-XUE** [comment]
hi @mrdeep1 , thank you for your answer.

So your mean is that I can choose one of the cipher suites from the mbedtls library to use, but I cannot add additional cipher suites. Right?
For example:
If I use cipher suites with PSK, there are 49 cipher suites in the client hello package, so I can choose one of these 49 cipher suites. Right?

My current situation is that I want to use TLS_PSK_WITH_AES_128_CCM_8 cipher suites, but I always choose TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 cipher suites in the server_hello package. (It is the first cipher suites in the cipher suites list in the client hello package.)
How do I choose the cipher suites from the mbedtls library?

**Comment by mrdeep1** [comment]
Yes, you can only use one of the cipher suites that your copy of the Mbed TLS is compiled for.

The client presents the list of (in this case PSK) ciphers supported, and then the server sees which ciphers it supports and then generally chooses the strongest cipher - hence why you are seeing TLS_PSK_WITH_AES_128_CCM_8 as one of the presented ciphers, but the server chooses TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 as the best one.

So, for what you want to do, you will need to update `set_ciphersuites()` to only add in TLS_PSK_WITH_AES_128_CCM_8 (id is 0xc0A8) into `psk_list[0]`, followed by a zero terminate in `psk_list[1`].  It is a very non-standard change though, and will not be supported as a part of standard libcoap.  E.G.
````
$ git diff src/coap_mbedtls.c
diff --git a/src/coap_mbedtls.c b/src/coap_mbedtls.c
index 6a2899b..ae434cd 100644
--- a/src/coap_mbedtls.c
+++ b/src/coap_mbedtls.c
@@ -1007,8 +1007,10 @@ set_ciphersuites(mbedtls_ssl_config *conf, coap_enc_method
           /* Minimum of TLS1.2 required - skip */
         }
         else if (mbedtls_ssl_ciphersuite_uses_psk(cur)) {
-          *psk_list = *list;
-          psk_list++;
+          if (*list == 0xc0A8) {
+            *psk_list = *list;
+            psk_list++;
+          }
         }
         else {
           *pki_list = *list;
````

**Comment by WEN-XUE** [comment]
hi @mrdeep1 , 

Thank you very much, I have successfully used other cipher suites.

>>The client presents the list of (in this case PSK) ciphers supported, and then the server sees which ciphers it supports and then >>generally chooses the strongest cipher - hence why you are seeing TLS_PSK_WITH_AES_128_CCM_8 as one of the presented >>ciphers, but the server chooses TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 as the best one.
I already know about this, thank you for your explanation.
