### ISSUE TITLE
Packet loss with CoAP over TCP

### ISSUE THREAD

**Issue by nourbouzid-donJu** [obgm/libcoap#680]
While running the examples CoAP server and CoAP client it seems like the -l loss% works only for CoAP over UDP. When running the client or server with -l parameters for CoAP over TCP no randomised packet loss takes place

**Comment by obgm** [comment]
You would expect TCP to handle any packet loss, so on the CoAP layer, this should have no immediate effect.

**Comment by mrdeep1** [comment]
UDP is an unreliable medium - there is no guarantee that a packet 'sent' will actually arrive.  TCP is a reliable medium in that if there is packet loss it will try to recover.  There is a guarantee that all the packets will arrive in the order that they are fed into the TCP stack or there is a overall failure.

CoAP adds in a layer of reliability when running over UDP - if Confirmable messaging is used - as it too has a recovery mechanism if packets do not arrive.  When running over TCP, there is no notion of Confirmable messages and hence no recovery support (CON. ACK, RST etc. are removed from the CoapProtocol RFC8323) - at it relies on the TCP layer to do the recovery work.

The `-l` option is there to stimulate packet loss at the UDP level so that CoAP recovery can be debugged and verified if need be.  libcoap has no control over how the TCP layer sending packets - dropping data when passed between the CoAP and TCP layer violates the principal of all the data being passed to the TCP layer for ongoing transmission.  Hence `-l` is not supported for TCP.

**Comment by nourbouzid-donJu** [comment]
Thank you for your response.
What if I want to trigger retransmissions for CoAP over TCP for experimental evaluation purposes?

**Comment by mrdeep1** [comment]
It would need to be done at the TCP/Ethernet layer.  Google for `simulate packet loss`.

**Comment by nourbouzid-donJu** [comment]
Thank you I shall close this issue
