### ISSUE TITLE
RIOT OS support

### ISSUE THREAD

**Issue by nourbouzid-donJu** [obgm/libcoap#681]
How can I run the latest version of libcoap (with support for CoAP over TCP) on Riot? I only found an outdated version.
Is there any documentation/example file for RIOT?

**Comment by obgm** [comment]
I have not yet finished updating the RIOT libcoap package to the release candidate for version 4.3. of libcoap. (Most changes need to be done on the packaging side, a little on libcoap's core.)

However, we have never had TCP support for CoAP on RIOT so far due to the (at that time) missing functionality on the BSD socket layer. Maybe it is time to put more effort in that.
