### ISSUE TITLE
Support for allowing OSCORE requests

### ISSUE THREAD

**Issue by BitFis** [obgm/libcoap#725]
**Is your feature request related to a problem? Please describe.**

Currently it seems to be not possible without changing code to implement Object Security (OSCORE) support due to the check of https://github.com/obgm/libcoap/blob/develop/src/net.c#L719-L743.

**Describe the solution you'd like**

OSCORE Messages with CoAP Option 9 (https://datatracker.ietf.org/doc/html/rfc8613#section-13.2) should
be passed to the application layer or somehow be possible to be encrypted through callback or some other way.

**Describe alternatives you've considered**

I manually added the bypassing by changing:

```patch
diff --git a/src/net.c b/src/net.c
index d883462..183d107 100644
--- a/src/net.c
+++ b/src/net.c
@@ -666,6 +666,7 @@ coap_option_check_critical(coap_context_t *ctx,
       case COAP_OPTION_PROXY_SCHEME:
       case COAP_OPTION_BLOCK2:
       case COAP_OPTION_BLOCK1:
+      case 9: // OSCORE option code [RFC8613] 
         break;
       default:
         if (coap_option_filter_get(ctx->known_options, opt_iter.type) <= 0) {
-- 
```

This allowed decoding of the OSCORE on the application layer.

**Additional context**

I found the issue #222, but it seems no work is beeing done anymore.

Thanks and keep up the great work ❤️

**Comment by obgm** [comment]
Thanks. OSCORE support is still in progress. There is a [working and tested contribution from Peter van der Stock](https://gitlab.informatik.uni-bremen.de/obergman/libcoap/-/tree/oscore) which needs a bit of cleanup and then integration into the current develop branch. Work is under way.
Regarding `coap_option_check_critical()`: The proper way to make a critical option that is not currently supported by the core library known to libcoap is to register it with `coap_register_option()` (note that you should pass `COAP_OPTION_OSCORE` instead of the plain number).

**Comment by BitFis** [comment]
Using `coap_register_option()` solved it. Currently I am not able to use the version from Peter van der Stock. Thank you for your help.
