### ISSUE TITLE
Single DTLS session for CoAP server&client

### ISSUE THREAD

**Issue by jqiaobln** [obgm/libcoap#772]
**Is your feature request related to a problem? Please describe.**

Currently the example code of libcoap has client and server as separate processes to be run: a server will be started and listen at a port until being shutdown; a client will open a different port (looks like) and abort as soon as its request is sent. Each process will start its own DTLS session.

**Describe the solution you'd like**

Is there a way to combine both into 1 process so only 1 DTLS session is needed for bi-directional requests/responses? For some power constraint devices, they need to enter sleep mode often and cannot have 1 permanent DTLS session running forever. 

**Describe alternatives you've considered**

I haven't thought of other alternatives, as bi-directional requests/responses (including block-wise transfer in both ways) are mandatory for my needs.

**Additional context**

Regarding block transfer support in CoAP server, I did find the '-L' option which enables block support, however there is no option to specify payload to transfer with? (Apologies to ask this question here as I cannot find answer in the documentation)

**Comment by mrdeep1** [comment]
From a DTLS perspective, the DTLS client needs to start a DTLS session to a DTLS serrver so that the DTLS protocol handshakes can correcltly take place, so establishing a DTLS session.  In theory, the DTLS client and DTLS server can be the same application with 2 different threads doing the DTLS client/server setup stuff, but I would say that this is a bad design.  DTLS is for protecting data as it traverses across a network.

CoAP RFC7252 does not specify that only the client application can make a request to a server application which then sends the response back.   A CoAP endpoint can have client supporting code (i.e able to make requests) and server supporting code (i.e able to respond to requests).  It is then upto the application running on the CoAP endpoint to decide what it wants to do.  Obviously the remote peer endpoint has to support the dual client/serverfunctionality.

The example code provided by libcoapfor the CoAP client only supports client side (request making) code.  The CoAP server - when acting as a man in the middle proxy, primarily has server side code support (for responding to a client) but additionally makes a secondary session to the CoAP Proxy's upstream CoAP server using client logic so that requests etc. can be passed on - but still is only supporting client requests on the secondary session.

>  a client will open a different port (looks like) and abort as soon as its request is sent.

A CoAP client does not need to close down after sending off a single request - the application can continue to send subsequent requests and process the corresponding responses.  The CoAP client usually randomly chooses the source port of the network session at startup (and continues to use that port) to differentiate between multiple (any application) clients so returning network trafic gets routed to the correct application. 

You may want to consider the CoAP server being able to send unsolicited responses using the Observe logic [RFC7641](https://datatracker.ietf.org/doc/html/rfc7641) [coap_observe(3)](https://libcoap.net/doc/reference/develop/man_coap_observe.html) so maintaining a simpler client / server relationship.  Otherwise you will need to craft the code to do what you want it to do.

The coap-client/coap-server -L option is used to tell libcoap how much it is the responsibility of libcoap to handle the multiple payloads of a large body transfer. See [coap_block(3)](https://libcoap.net/doc/reference/develop/man_coap_block.html)

**Comment by mrdeep1** [comment]
@jqiaobln Do you have any further questions against my response.  Otherwise, can you please close this Issue if you are happy with the response.
