### ISSUE TITLE
How to release coap_resource_t independently in the absence of coap_context_t？

### ISSUE THREAD

**Issue by SproutOrc** [obgm/libcoap#788]
How to release coap_resource_t independently in the absence of coap_context_t？

**Comment by mrdeep1** [comment]
Any created `coap_resource_t*` is linked onto the `coap_context_t*` chain using `coap_add_resource()` so that libcoap recognizes it as a valid resource.  Therefore, when releasing a `coap_resource_t*` it also needs to be removed from the `coap_context_t*` chain so that libcoap does not try to use memory that is not longer properly formatted.

If you are operating in a call-back handler, then the `coap_context_t*` may not be there.  However, there should be a `coap_session_t*`, and this can be used in `coap_session_get_context()` (See [coap_session(3)](https://libcoap.net/doc/reference/develop/man_coap_session.html)) to get the `coap_context_t*` to use for releasing `coap_resource_t*`.

**Comment by SproutOrc** [comment]
I'm very sorry I didn't describe my problem in detail. 

I mean to do something between coap_resource_init and coap_add_resource; if something goes wrong I will need to call the release function of the resource; but now I have to add the resource to the context first and then call coap_delete_resource.

**Comment by SproutOrc** [comment]
Glad to receive your reply; thank you
