### ISSUE TITLE
Sending multiple requests then waiting for replies

### ISSUE THREAD

**Issue by PMunch** [obgm/libcoap#846]
## Environment

- libcoap version (run ``git describe --tags`` to find it):

    // 4.3.0-1
- Build System:            Unknown
- Operating System:         Linux
- Operating System Version: 5.4.188
- Hosted Environment:       None

## Problem Description

Hello, I am trying to use libcoap to interface with an existing CoAP server. I'm trying to get information about multiple entities in the system and therefore I tried to run multiple send requests at once and then wait for the results in a response handler. However it seems to lock up after having received a couple of entities. According to the debug log from libcoap all the requests except the first are "delayed". Once the first one comes in the second is "transmitted after delay", however once I get a response from that one nothing more seems to happen, and the program just hangs forever.

I'm periodically calling `coap_io_process` and checking `coap_can_exit`, the latter returns 0, but `coap_io_process` doesn't appear to send any of the messages.

Since I'm trying to create something which can be reused by others I'm using the libcoap version from my package manager, this is version 4.3.0-1.

### Expected Behavior

Messages to be sent as soon as possible and responses to be returned by the callback

### Actual Behavior

See above, messages don't appear to be sent even though `coap_send` returns an ID.

### Steps to reproduce

1. Send more than one request at a time

### Code to reproduce this issue

I'm wrapping this in a language which does C interop, I'm afraid the addition of code here would only confuse the matter.

## Debug Logs

```
May 08 00:07:36.252 DEBG *  192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: sent 45 bytes
v:1 t:CON c:GET i:b8dd
May 08 00:07:36.252 DEBG ** 192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: mid=0xb8dd: added to retransmit queue (2500ms)
May 08 00:07:36.252 DEBG ** 192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: mid=0xb8de: delayed
May 08 00:07:36.252 DEBG ** 192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: mid=0xb8df: delayed
May 08 00:07:36.252 DEBG ** 192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: mid=0xb8e0: delayed
May 08 00:07:36.254 DEBG *  192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: received 364 bytes
v:1 t:ACK c:2.05 i:b8dd
May 08 00:07:36.254 DEBG ** 192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: mid=0xb8dd: removed
May 08 00:07:36.254 DEBG ** 192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: mid=0xb8de: transmitted after delay
May 08 00:07:36.254 DEBG *  192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: sent 45 bytes
v:1 t:CON c:GET i:b8de
May 08 00:07:36.254 DEBG ** 192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: mid=0xb8de: added to retransmit queue (2281ms)
May 08 00:07:36.254 DEBG ** 192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: mid=0xb8de: removed
May 08 00:07:36.256 DEBG *  192.168.1.146:38638 <-> 192.168.1.69:5684 DTLS: received 365 bytes
v:1 t:ACK c:2.05 i:b8de
```

## Other items if possible

Everything works fine if I send a request, wait for a response in the callback, and then send the next request
Everything is done on a local network, both the machine I'm running this on and the server are connected to the same router with cables.

**Comment by mrdeep1** [comment]
According to the NSTART rules of RFC7252, only one Confirmable Request/ Response can be in flight at any one time - hence why subsequent requests are delayed - so that is normal.

Each Request should have a unique Token (RFC 9175) to remove any response confusion.

When a response comes back, it should trigger the next outstanding request. This can fail if multiple threads are doing the requests.

There has been some work in to tighten things up in this area post 4.3.0 in the develop branch.  Once you have implemented unique tokens per request (see latest examples/coap-client.c), and there still are issues, please test your code out against the latest develop branch which gives more diagnostic messages.

**Comment by mrdeep1** [comment]
A quick test shows that all works when you use unique token per request, but fails when using no token in post 4.3.0 code

**Comment by PMunch** [comment]
I figured the delays where parts of the RFC.

Isn't the ID each request gets enough to remove response confusion? If not, what is the ID for?

The entire program is run on a single thread, so that shouldn't be an issue here.

If it is an error to queue multiple messages without tokens, maybe this should throw an error instead of just locking up the entire system?

**Comment by mrdeep1** [comment]
The Message ID (MID) is for matching low level request/response.  The Token is used for matching applicaction request/response.

For Confirmable requests, the response (containing the data) can be piggybacked, or sent separately.  In the former, MID and Token matching is used, in the latter, receipt of the response is matched (using an empty ACK sent by the server) by the MID and then when the server sends the actual data, it uses a different MID but the same Token so that the client can match up the data request with the data response.

[[5.3](https://www.rfc-editor.org/rfc/rfc7252.html#section-5.3).  Request/Response Matching](https://www.rfc-editor.org/rfc/rfc7252.html#section-5.3) defines how the application layer should be doing the matching.

[[5.3.2](https://www.rfc-editor.org/rfc/rfc7252.html#section-5.3.2).  Request/Response Matching Rules](https://www.rfc-editor.org/rfc/rfc7252.html#section-5.3.2) defines the matching rules.

The MID matching part of the libcoap logic looks to be fine.  The issue is when a Token is received (even if it is a zero length token) the logic effectively says 'token in response is no longer needed, remove any pending queued entries with the same token', which unfortunately causes confusion for the subsequent sending of further queued/delayed requests.

I will look to see if the libcoap logic could be a bit smarter here in handling multiple (which could be individually different) requests that hit the NSTART limit, but the right answer here is to be using different Tokens.

**Comment by mrdeep1** [comment]
I appreciate that you are having to use a 4.3.0 build, but can you please try the following change to the 4.3.0 code
````
diff --git a/src/net.c b/src/net.c
--- a/src/net.c
+++ b/src/net.c
@@ -2902,7 +2902,8 @@ handle_response(coap_context_t *context, coap_session_t *session,
    * been lost, so we need to stop retransmitting requests with the
    * same token.
    */
-  coap_cancel_all_messages(context, session, rcvd->token, rcvd->token_length);
+  if (rcvd->type != COAP_MESSAGE_ACK)
+    coap_cancel_all_messages(context, session, rcvd->token, rcvd->token_length);
 
   if (session->block_mode & COAP_BLOCK_USE_LIBCOAP) {
     /* See if need to send next block to server */

````
or against the latest develop code
````
diff --git a/src/net.c b/src/net.c
index 4c08549..dd96858 100644
--- a/src/net.c
+++ b/src/net.c
@@ -3035,7 +3040,7 @@ handle_response(coap_context_t *context, coap_session_t *session,
    * been lost, so we need to stop retransmitting requests with the
    * same token.
    */
-  if (rcvd->type == COAP_MESSAGE_ACK)
+  if (rcvd->type != COAP_MESSAGE_ACK)
     coap_cancel_all_messages(context, session, rcvd->token, rcvd->token_length);

   if (session->block_mode & COAP_BLOCK_USE_LIBCOAP) {
````
and let me know hif it fixes what you are seeing.

**Comment by mrdeep1** [comment]
The fix above is only a partial fix, which should work for your specific scenario.

When using the same (could be 0 length) token in multiple Confirmable (CON) requests, there is a window between where the request is sent and the response received (MID matches) where a separate (not piggybacked) or unsolicited (i.e. Observe) response is received in the window and `coap_cancel_all_messages()` gets called.  The CoAP RFCs state that the separate or unsolicited response can be CON or Non-confirmable (NON).

`coap_cancel_all_messages()` is required for the scenario where a CON request is sent, an empty ACK response (same MID) is sent back (but gets dropped) followed by the CON (or NON) separate response which is received (different MID) that has a token match.  The CON request needs to be removed from the send-queue to stop timeout re-transmissions of the original CON request because an ACK was never received.

With unique tokens per request `coap_cancel_all_messages()` will only clean up the correct items.

**Comment by PMunch** [comment]
I tried attaching a token and I can confirm that that worked perfectly fine. Haven't tried the above patch though, as I'd have to set up compilation of libcoap in order to do so and I haven't found the time to do so yet.

**Comment by mrdeep1** [comment]
Using tokens is the right way forward - thanks for confirming that it works for you.  

The suggested patch does not cover all cases when not using tokens (or using the same token), so no need to spend time trying that out.

Not using tokens is an easy trap to fall into, but actually difficult to  detect and warn against with multiple scenarios beyond your specific one.  Inspiration may come as to how to do this for all scenarios.
