### ISSUE TITLE
Add support for CoAP over WebSocket

### ISSUE THREAD

**Issue by woobagooba** [obgm/libcoap#968]
As described in https://datatracker.ietf.org/doc/html/rfc8323

There is interest for applications communicating with cloud services over costly cellular and satellite links which also have premises NAT in the comms path.

**Comment by mrdeep1** [comment]
I see very little difference between `coap+tcp://` and `coap+ws://` (or `coaps+tcp://` and `coaps+ws://`) in terms of traffic going over the wire as they all run over TCP.  There is a marginal increase in set up time for `coap+ws://` and `coaps+ws://`, overhead for the websocket framing as well as for the session close.  So, I would be expecting traffic increases using WebWockets with no differences with handling interim NAT devices.  But I could be missing something here.

libcoap would need another layer to pass through in the stack of
````
CoAP API
----------Managed by libcoap --------------------
CoAP Processing
WebSocket layer (optional)
(D)TLS layer (optional)
----------Managed by libcoap --------------------
TCP or UDP
````
which could be a good project for someone to take on using a third party websockets library.  Any takers?

**Comment by adriansmares** [comment]
Outside of the NAT traversal argument raised originally, an additional advantage of initializing the connection via HTTP is that the initial request contains metadata that can help load balancers and (reverse-)proxies along the way. And these load balancers do not need to understand CoAP in order to decide to which underlying service should the request - they just need to parse the HTTP headers, path and method before the connection is upgraded to WebSocket.

This enables the use of already existing HTTP load balancing solutions (such as [nginx](https://www.nginx.com/), [traefik](https://traefik.io/) or even cloud native solution such as [AWS Application Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html)) to route the CoAP tunnel to the correct backend service without supporting CoAP themselves.

**Comment by obgm** [comment]
> someone to take on using a third party websockets library. Any takers?

There may be in 1Q2023. I am taking this for now.

**Comment by mrdeep1** [comment]
@AkashSinha007 It is good that you are spending time investigating things and learning from them.

Unfortunately, libcoap looks for traffic at the TCP/UDP level by monitoring set up sockets.  The (D)TLS layer (assuming it is enabled) is given a received packet for either (D)TLS handshake or (D)TLS decryption.  The TLS library calls a defined callback with the decrypted packet which is then passed on up the libcoap stack.  Likewise, when libcoap has a packet to send, it is passed to the TLS Library for encryption which then invokes a callback to send out the encrypted packet over the appropriate socket.

So, the cleanest way is for the Websockets layer to be following a similar model - especially if the packets (including websockets headers) are to be encrypted.

The challenges I initially see with using Javascript as a man-in-the-middle (Client...Websocket<>TCP...Server+libcoap) is that it would have to handle the `Upgrade: websocket` message as well then correcting the length field to/from len=0 so that TCP CoAP understands what is going on.

**Comment by woobagooba** [comment]
Happy New Year.  Any news regarding support for Websocket?

**Comment by mrdeep1** [comment]
@obgm Did you manage to allocate this?

**Comment by tbejer** [comment]
Hi 
I have two questions regarding CoAP over WebSocket:

- In http://www.watersprings.org/pub/id/draft-ietf-core-coap-tcp-tls-06.html#examples 
  an example of the connection set-up scenario is described. 
  Will this be valid for this implementation too?

- After setting up a WebSocket connection, it may be used in both directions for requests/responses. 
   Will this feature be supported too, so the client may set up a connection and send a request, get a response.
   May the server then use this WS connection to send CoAP requests to the original client?

Best regards

**Comment by hasheddan** [comment]
@obgm do you have work on this currently in progress? If not, I’d love to pick this up to work on!

**Comment by mrdeep1** [comment]
@hasheddan Happy to work with you on this.

I have been steadily working towards breaking down the libcoap library into different layers (some of the code already merged into the develop branch).  I am currently debugging some code where the different layers are invoked depending on which CoAP protocol is being used in the session which considerably simplifies adding in a new layer such as WebSockets.

I do have an initial POC code for WebSockets layer that does not yet do the initial or close handshakes but successfully transfers the wrapped CoAP packets (using TLS if wanted).  This POC needs tidying up before making it available.

**Comment by mrdeep1** [comment]
I should be able to share it with you early next week.  I think the code is basically handling the RFC8323 side of things, it needs the Websockets RFC6455 handling to be properly added.

**Comment by woobagooba** [comment]
Thanks everyone for your continued effort on this feature.

**Comment by obgm** [comment]
> @obgm do you have work on this currently in progress? If not, I’d love to pick this up to work on!

@hasheddan Thanks! :heart: Please feel free to work with @mrdeep1 to move this topic forward.

**Comment by mrdeep1** [comment]
@hasheddan Initial code is in https://github.com/mrdeep1/libcoap/tree/websockets , the principals are there, I still have some work to do on the protocol layers.   I have found coaps+ws:// to be unstable, and am looking into why.  I will be pushing any changes I find there.

Main work to be done is in src/coap_ws.c. In particular the negotiating headers and hashing the client's transmissions.

It would best to initially do things via email - address is at head of coap_ws.c.

**Comment by Wi-SUN** [comment]
Thank you @mrdeep1  . Please clarify, will this PR build or is build not possible due to LwIP issues?

**Comment by mrdeep1** [comment]
@Wi-SUN The github/LwIP issue has been fixed.  This PR will now build (and has successfully built as per the github status flags).

**Comment by mrdeep1** [comment]
Support for WebSockets is now available in the develop branch.  As SHA1 is required, the libcoap library currently needs to be built with OpenSSL, GnuTLS or Mbed TLS.
